*B/C5 – Regulations for reporting SYNOP MOBIL data in TDCF*

*TM 307090 – BUFR template for synoptic reports from mobile land stations suitable for SYNOP MOBIL data*

[cols=",,",]
|===
| | |*Sequence for representation of synoptic reports from a mobile land station suitable for SYNOP MOBIL data*
|*3 07 090* |*3 01 092* |*Mobile surface station identification, date/time, horizontal and vertical coordinates*
| |*3 02 031* |*Pressure information*
| |*3 02 035* |*Basic synoptic “instantaneous” data*
| |*3 02 036* |*Clouds with bases below station level*
| |*3 02 047* |*Direction of cloud drift*
| |*0 08 002* |*Vertical significance (surface observations)*
| |*3 02 048* |*Direction and elevation of cloud*
| |*3 02 037* |*State of ground, snow depth, ground minimum temperature*
| |*3 02 043* |*Basic synoptic “period” data*
| |*3 02 044* |*Evaporation data*
| |*1 01 002* |*Replicate 1 descriptor 2 times*
| |*3 02 045* |*Radiation data (from 1 hour and 24-hour period)*
| |*3 02 046* |*Temperature change*
|===

This BUFR template for synoptic reports from mobile land stations further expands as follows:

[cols=",,,,",]
|===
| | | | |Unit, scale
| | | |*Mobile surface station identification, date/time, horizontal and vertical coordinates* |
|*3 01 092* |0 01 011 | |Ship or mobile land station identifier D….D |CCITT IA5, 0
| |0 01 003 | |WMO Region number/geographical area A~1~ |Code table, 0
| |0 02 001 | |Type of station i~x~ |Code table, 0
| |3 01 011 |0 04 001 |Year |Year, 0
| | |0 04 002 |Month |Month, 0
| | |0 04 003 |Day YY |Day, 0
| |3 01 012 |0 04 004 |Hour GG |Hour, 0
| | |0 04 005 |Minute gg |Minute, 0
| |3 01 021 |0 05 001 |Latitude (high accuracy) L~a~L~a~L~a~ |Degree, 5
| | |0 06 001 |Longitude (high accuracy) L~o~L~o~L~o~L~o~ |Degree, 5
| |0 07 030 | |Height of station ground above mean sea level |m, 1
| |0 07 031 | |Height of barometer above mean sea level |m, 1
| |0 33 024 | |Station elevation quality mark i~m~ |Code table, 0
| | | |*Pressure information* |
|*3 02 031* |3 02 001 |0 10 004 |Pressure P~0~P~0~P~0~P~0~ |Pa, –1
| | |0 10 051 |Pressure reduced to mean sea level PPPP |Pa, –1
| | |0 10 061 |3-hour pressure change ppp |Pa, –1
| | |0 10 063 |Characteristic of pressure tendency a |Code table, 0
| |0 10 062 | |24-hour pressure change p~24~p~24~p~24~ |Pa, –1
| |0 07 004 | |Pressure (standard level) a~3~ |Pa, –1
| |0 10 009 | |Geopotential height (of the standard level) hhh |gpm, 0
| | | |*Basic synoptic “instantaneous” data* |
|*3 02 035* | | |_Temperature and humidity data_ |
| |*3 02 032* |0 07 032 |Height of sensor above local ground (or deck of marine platform) +
(for temperature and humidity measurement) |m, 2
| | |0 12 101 |Temperature/air temperature s~n~TTT |K, 2
| | |0 12 103 |Dewpoint temperature s~n~T~d~T~d~T~d~ |K, 2
| | |0 13 003 |Relative humidity |%, 0
| | | |_Visibility data_ |
| a|
=== 3 02 033

a|
=== 0 07 032

|Height of sensor above local ground (or deck of marine platform) +
(for visibility measurement) |m, 2
| | |0 20 001 |Horizontal visibility VV |m, –1
| | | |_Precipitation past 24 hours_ |
| |*3 02 034* |0 07 032 a|
====== Height of sensor above local ground (or deck of marine platform) +
(for precipitation measurement)

|m, 2
| | |0 13 023 |Total precipitation past 24 hours R~24~R~24~R~24~R~24~ |kg m^–2^, 1
| |0 07 032 | |Height of sensor above local ground (or deck of marine platform) +
(set to missing to cancel the previous value) |m, 2
| | | |_General cloud information_ |
| |3 02 004 |0 20 010 |Cloud cover (total) N |%, 0
| | |0 08 002 |Vertical significance *(surface observations)* |Code table, 0
| | |0 20 011 |Cloud amount (of low or middle clouds) N~h~ |Code table, 0
| | |0 20 013 |Height of base of cloud h |m, –1
| | |0 20 012 |Cloud type (low clouds C~L~) C~L~ |Code table, 0
| | |0 20 012 |Cloud type (middle clouds C~M~) C~M~ |Code table, 0
| | |0 20 012 |Cloud type (high clouds C~H~) C~H~ |Code table, 0
| | | |*_Individual cloud layers or masses_* |
| |1 01 000 | |Delayed replication of 1 descriptor |
| |0 31 001 | |Delayed descriptor replication factor |Numeric, 0
| |3 02 005 |0 08 002 |Vertical significance *(surface observations)* |Code table, 0
| | |0 20 011 |Cloud amount N~s~ |Code table, 0
| | |0 20 012 |Cloud type C |Code table, 0
| | |0 20 013 |Height of base of cloud h~s~h~s~ |m, –1
| | | |*Clouds with bases below station level* |
|*3 02 036* |1 05 000 | |Delayed replication of 5 descriptors |
| |0 31 001 | |Delayed descriptor replication factor |Numeric, 0
| |0 08 002 | |Vertical significance *(surface observations)* |Code table, 0
| |0 20 011 | |Cloud amount N’ |Code table, 0
| |0 20 012 | |Cloud type C’ |Code table, 0
| |0 20 014 | |Height of top of cloud H’H’ |m, –1
| |0 20 017 | |Cloud top description C~t~ |Code table, 0
| | | |*Direction of cloud drift* group 56D~L~D~M~D~H~ |
|*3 02 047* |1 02 003 | |Replicate 2 descriptors 3 times |
| |0 08 002 | a|
Vertical significance *(surface observations) +
* = 7 (low cloud)

= 8 (middle cloud)

= 9 (high cloud)

|Code table, 0
| |0 20 054 | a|
True direction from which a phenomenon or clouds are moving or in which they are observed

D~L~, D~M~, D~H~

|Degree true, 0
|*0 08 002* | | a|
Vertical significance *(surface observations)*

(set to missing to cancel the previous value)

|Code table, 0
| | | |*Direction and elevation of cloud* gr. 57CD~a~e~C~ |
|*3 02 048* |0 05 021 | |Bearing or azimuth D~a~ |Degree true, 2
| |0 07 021 | |Elevation e~C~ |Degree, 2
| |0 20 012 | |Cloud type C |Code table, 0
| |0 05 021 | |Bearing or azimuth +
(set to missing to cancel the previous value) |Degree true, 2
| |0 07 021 | |Elevation +
(set to missing to cancel the previous value) |Degree, 2
| | | |*State of ground, snow depth, ground minimum temperature* |
|*3 02 037* |0 20 062 | |State of the ground (with or without snow) E or E’ |Code table, 0
| |0 13 013 | |Total snow depth sss |m, 2
| |0 12 113 | |Ground minimum temperature, past 12 hours s~n~T~g~T~g~ |K, 2
| | | |*Basic synoptic “period” data* |
| | | |_Present and past weather_ |
|*3 02 043* |*3 02 038* |0 20 003 |Present weather ww |Code table, 0
| | |0 04 024 |Time period or displacement (in hours) |Hour, 0
| | |0 20 004 |Past weather (1) W~1~ |Code table, 0
| | |0 20 005 |Past weather (2) W~2~ |Code table, 0
| a|
=== 

a|
=== 

|_Sunshine data (from 1 hour and 24-hour +
period)_ |
| |*1 01 002* | |Replicate 1 descriptors 2 times |
| |*3 02 039* |0 04 024 |Time period or displacement (in hours) |Hour, 0
| | |0 14 031 |Total sunshine SS *and* SSS |Minute, 0
| | | |_Precipitation measurement_ |
| |*3 02 040* |0 07 032 |Height of sensor above local ground (or deck of marine platform) +
(for precipitation measurement) |m, 2
| | |1 02 002 |Replicate 2 descriptors 2 times |
| | |0 04 024 |Time period or displacement (in hours) t~R~ |Hour, 0
| | |0 13 011 |Total precipitation/total water equivalent +
(of snow) RRR |kg m^–2^, 1
| | | |_Extreme temperature data_ |
| |*3 02 041* |0 07 032 |Height of sensor above local ground (or deck of marine platform) +
(for temperature measurement) |m, 2
| | |0 04 024 |Time period or displacement |Hour, 0
| | |0 04 024 |Time period or displacement (see Notes 1 and 2) |Hour, 0
| | |0 12 111 |Maximum temperature, at height and over period specified s~n~T~x~T~x~T~x~ |K, 2
| | |0 04 024 |Time period or displacement |Hour, 0
| | |0 04 024 |Time period or displacement (see Note 2) |Hour, 0
| | |0 12 112 |Minimum temperature, at height and over period specified s~n~T~n~T~n~T~n~ |K, 2
| | | |_Wind data_ |
| |*3 02 042* |0 07 032 |Height of sensor above local ground (or deck of marine platform) +
(for wind measurement) |m, 2
| | |0 02 002 a|
Type of instrumentation for wind measurement

i~w~

|Flag table, 0
| | |0 08 021 |Time significance (= 2 (time averaged)) |Code table, 0
| | |0 04 025 |Time period or displacement (= –10 minutes, or number of minutes after a significant change of wind) |Minute, 0
| | |0 11 001 |Wind direction dd |Degree true, 0
| | |0 11 002 |Wind speed ff |m s^–1^, 1
| | |0 08 021 |Time significance (= missing value) |Code table, 0
| | |1 03 002 |Replicate 3 descriptors 2 times |
| | |0 04 025 |Time period or displacement (in minutes) |Minute, 0
| | |0 11 043 |Maximum wind gust direction |Degree true, 0
| | |0 11 041 |Maximum wind gust speed 910f~m~f~m~, 911f~x~f~x~ |m s^–1^, 1
| |0 07 032 a|
=== 

|Height of sensor above local ground (or deck of marine platform) +
(set to missing to cancel the previous value) |m, 2
| | a|
=== 

|*Evaporation data* |
|*3 02 044* |0 04 024 | |Time period or displacement (in hours) |Hour, 0
| |0 02 004 | |Type of instrument for evaporation measurement or type of crop for which evapotranspiration is reported i~E~ |Code table, 0
| |0 13 033 | |Evaporation/evapotranspiration EEE |kg m^–2^, 1
| | a|
=== 

|*Radiation data (from 1 hour and 24-hour period)* |
|*1 01 002* | | |Replicate 1 descriptor 2 times |
|*3 02 045* |0 04 024 | |Time period or displacement (in hours) |Hour, 0
| |0 14 002 | a|
Long-wave radiation, integrated over period specified +
553SS 4FFFF or 553SS 5FFFF,

**55SSS 4**F~24~F~24~F~24~F~24~ **or 55SSS 5**F~24~F~24~F~24~F~24~

|J m^–2^, –3
| a|
=== 0 14 004

a|
=== 

|Short-wave radiation, integrated over period specified +
553SS 6FFFF, *55SSS* 6F~24~F~24~F~24~F~24~ |J m^–2^, –3
| |0 14 016 | a|
Net radiation, integrated over period specified

553SS 0FFFF or 553SS 1FFFF,

**55SSS 0**F~24~F~24~F~24~F~24~ **or 55SSS 1**F~24~F~24~F~24~F~24~

|J m^–2^, –4
| |0 14 028 | |Global solar radiation (high accuracy), integrated over period specified +
553SS 2FFFF, *55SSS* 2F~24~F~24~F~24~F~24~ |J m^–2^, –2
| |0 14 029 | |Diffuse solar radiation (high accuracy), integrated over period specified +
553SS 3FFFF, *55SSS* 3F~24~F~24~F~24~F~24~ |J m^–2^, –2
| |0 14 030 | |Direct solar radiation (high accuracy), integrated over period specified +
55408 4FFFF, *55508* 5F~24~F~24~F~24~F~24~ |J m^–2^, –2
| | | |*Temperature change* group 54g~0~s~n~d~T~ |
|*3 02 046* |0 04 024 | |Time period or displacement |Hour, 0
| |0 04 024 | |Time period or displacement (see Note 3) |Hour, 0
| |0 12 049 | |Temperature change over specified period s~n~d~T~ |K, 0
|===

Notes:

{empty}(1) Within RA-IV, the maximum temperature at 1200 UTC is reported for the previous calendar day (i.e. the ending time of the period is not equal to the nominal time of the report). To construct the required time range, descriptor 0 04 024 has to be included two times. If the period ends at the nominal time of the report, value of the second 0 04 024 shall be set to 0.

{empty}(2) Within RA-III, the maximum daytime temperature and the minimum night-time temperature is reported (i.e. the ending time of the period may not be equal to the nominal time of the report). To construct the required time range, descriptor 0 04 024 has to be included two times. If the period ends at the nominal time of the report, value of the second 0 04 024 shall be set to 0.

{empty}(3) To construct the required time range, descriptor 0 04 024 has to be included two times.

* +
Regulations:*

*B/C5.1 Section 1 of BUFR or CREX*

*B/C5.2 Mobile surface station identification, date/time, horizontal and vertical coordinates*

*B/C5.3 Pressure information*

*B/C5.4 Basic synoptic “instantaneous” data*

*B/C5.4.1 Temperature and humidity data*

*B/C5.4.2 Visibility data*

*B/C5.4.3 Precipitation past 24 hours*

*B/C5.4.4 General cloud information*

*B/C5.4.5 Individual cloud layers or masses*

*B/C5.5 Clouds with bases below station level*

*B/C5.6 Direction of cloud drift*

*B/C5.7 Direction and elevation of cloud*

*B/C5.8 State of ground, snow depth, ground minimum temperature*

*B/C5.9 “Instantaneous” data required by regional or national reporting practices*

*B/C5.10 Basic synoptic “period” data*

*B/C5.10.1 Present and past weather*

*B/C5.10.2 Sunshine data (from 1 hour and 24-hour period)*

*B/C5.10.3 Precipitation measurement*

*B/C5.10.4 Extreme temperature data*

*B/C5.10.5 Wind data*

*B/C5.11 Evaporation data*

*B/C5.12 Radiation data (from 1 hour and 24-hour period)*

*B/C5.13 Temperature change*

*B/C5.14 “Period” data required by regional or national reporting practices*

*B/C5.1 Section 1 of BUFR or CREX*

*B/C5.1.1 Entries required in Section 1 of BUFR*

____
*The following entries shall be included in BUFR Section 1:*

– *BUFR master table;*

– *Identification of originating/generating centre;*

– *Identification of originating/generating sub-centre;*

– *Update sequence number;*

– *Identification of inclusion of optional section;*

– *Data category (= 000 for SYNOP MOBIL data);*

– *International data sub-category (see Notes 1 and 2);*

– *Local data sub-category;*

– *Version number of master table;*

– *Version number of local tables;*

– *Year (year of the century up to BUFR edition 3);*

– *Month (standard time);*

– *Day (standard time = YY in the* abbreviated telecommunication header *for SYNOP MOBIL data*);

– *Hour (standard time = GG in the* abbreviated telecommunication header *for SYNOP MOBIL data*);

– *Minute (standard time = 00 for SYNOP MOBIL data);*

– *Second (= 0) (see Note 1).*

*Notes:*

*(1) Inclusion of this entry is required starting with BUFR edition 4.*

*(2) If required, the international data sub-category shall be included for SYNOP MOBIL data as:*

*= 005 at main synoptic times 00, 06, 12, 18 UTC;*

*= 004 at intermediate synoptic times 03, 09, 15, 21 UTC;*

*= 003 at observation times 01, 02, 04, 05, 07, 08, 10, 11, 13, 14, 16, 17, 19, 20, 22 and 23 UTC.*

**(3) If an NMHS performs conversion of SYNOP MOBIL data produced by another NMHS, o**riginating centre in Section 1 shall indicate **the converting centre and o**riginating sub-centre shall indicate the *producer of SYNOP MOBIL bulletins. Producer of SYNOP MOBIL bulletins shall be specified in Common Code table C-12 as a sub-centre of the originating centre, i.e. of the NMHS executing the conversion.*
____

*B/C5.1.2 Entries required in Section 1 of CREX*

____
*The following entries shall be included in CREX Section 1:*

– *CREX master table;*

– *CREX edition number;*

– *CREX table version number;*

– *Version number of BUFR master table (see Note 1);*

– *Version number of local tables (see Note 1);*

– *Data category (= 000 for SYNOP MOBIL data);*

– *International data sub-category (see Notes 1 and 2);*

– *Identification of originating/generating centre (see Note 1);*

– *Identification of originating/generating sub-centre (see Note 1);*

– *Update sequence number (see Note 1);*

– *Number of subsets (see Note 1);*

– *Year (standard time) (see Note 1);*

– *Month (standard time) (see Note 1);*

– *Day (standard time = YY in the* abbreviated telecommunication header *for SYNOP MOBIL data*) *(see Note 1);*

– *Hour (standard time = GG in the* abbreviated telecommunication header *for SYNOP MOBIL data*) *(see Note 1);*

– *Minute (standard time = 00 for SYNOP MOBIL data) (see Note 1).*

*Notes:*

*(1) Inclusion of these entries is required starting with CREX edition 2.*

*(2) If inclusion of international data sub-category is required, Note 2 under B/C5.1.1 applies.*

*(3) If an NMHS performs conversion of SYNOP MOBIL data produced by another NMHS, Note 3 under B/C5.1.1 applies.*
____

*B/C5.2 Mobile surface station identification, date/time, horizontal and vertical coordinates <3 01 092>*

*B/C5.2.1 Mobile surface station identification*

____
Mobile land station identifier (0 01 011) shall be always reported as a non-missing value. In the absence of a suitable call sign, the word MOBIL shall be used for mobile land station identifier. [12.1.7(c)]

WMO regional number (0 01 003) shall be reported to indicate the geographical area in which the mobile station has been deployed.

Type of station (Code table 0 02 001) shall be reported to indicate the type of the station operation (manned, automatic or hybrid).

Note: If a station operates as a manned station for a part of the day and as an automatic station for the rest of the day, code figure 2 (Hybrid) may be used in all reports. It is preferable, however, to use code figure 1 (Manned) in reports produced under the supervision of an observer, and a code figure 0 (Automatic) in reports produced while the station operates in the automatic mode.
____

*B/C5.2.2 Time of observation*

____
Year (0 04 001), month (0 04 002), day (0 04 003), hour (0 04 004) and minute (0 04 005) of the actual time of observation shall be reported.

Note: The actual time of observation shall be the time at which the barometer is read. [12.1.6]
____

*B/C5.2.2.1* If the actual time of observation differs by 10 minutes or less from the standard time reported in Section 1, the standard time may be reported instead of the actual time of observation. [12.2.8]

*B/C5.2.3 Horizontal and vertical coordinates*

____
*Latitude (0 05 001) and longitude* (0** **06 001) of the station shall be reported in degrees with precision in 10^–5^ of a degree.

Height of station ground above mean sea level (0 07 030) and height of barometer above mean sea level (0 07 031) shall be reported in metres with precision in tenths of a metre.
____

*B/C5.2.4 Station elevation quality mark* – Code table 0 33 024

____
Station elevation quality mark shall be reported to indicate the accuracy of the vertical coordinates of the mobile station.
____

*B/C5.3 Pressure information <3 02 031>*

*B/C5.3.1 Pressure at the station level*

____
Pressure at the station level (0 10 004), i.e. at the level defined by 0 07 031 (height of barometer above mean sea level), shall be reported in pascals (with precision in tens of pascals).
____

*B/C5.3.1.1* The station pressure shall be included in reports for global exchange from land stations, together with either the mean sea level pressure or, in accordance with Regulation B/C5.3.5.1, with the geopotential height of a standard pressure level.

____
Note: Inclusion of the station pressure at other times is left to the decision of individual Members.

{empty}[12.2.4]
____

*B/C5.3.2 Pressure* *reduced to mean sea level*

____
Pressure reduced to mean sea level (0 10 051) shall be reported in pascals (with precision in tens of pascals).
____

*B/C5.3.2.1* Whenever air pressure at mean sea level can be computed with reasonable accuracy, this pressure shall be reported.

____
Notes:

{empty}(1) For a station situated in a region of normal synoptic network density, the pressure at mean sea level is considered not to be computed with reasonable accuracy when it introduces a deformation into the analysis of the horizontal pressure field, which is purely local and recurring.

{empty}(2) For a station lying in a data-sparse area of the synoptic network, reasonable accuracy will be obtained when using a reduction method, which has proved to be satisfactory in a region of normal network density and under similar geographic conditions.

{empty}[12.2.3.4.1]
____

*B/C5.3.3 Three-hour pressure change and characteristic of pressure tendency*

____
Amount of pressure change at station level, during the three hours preceding the time of observation (0 10 061), either positive, zero _or negative_, shall be reported in pascals (with precision in tens of pascals).
____

*B/C5.3.3.1* Unless specified otherwise by regional decision, pressure tendency shall be included whenever the three-hourly pressure tendency is available. [12.2.3.5.1]

*B/C5.3.3.2* The characteristic of pressure tendency (Code table 0 10 063) over the past three hours shall, whenever possible, be determined on the basis of pressure samples at equi-spaced intervals not exceeding one hour.

____
Note: Algorithms for selecting the appropriate code figure are included in the _Guide to Meteorological Instruments and Methods of Observation_ (WMO-No. 8).

{empty}[12.2.3.5.2]
____

*B/C5.3.3.3* Where it is not possible to apply the algorithms specified in Regulation B/C5.3.3.2 in reports from automatic weather stations, the characteristic of pressure tendency shall be reported as 2 when the tendency is positive, as 7 when the tendency is negative, and as 4 when the atmospheric pressure is the same as three hours before. [12.2.3.5.3]

*B/C5.3.4 24-hour pressure change*

____
If specified by regional decision, amount of surface pressure change at station level, during 24 hours preceding the time of observation (0 10 062), either positive, zero or negative, shall be reported in pascals (with precision in tens of pascals). [12.4.7.1.2(k), (l)]
____

*B/C5.3.5 Geopotential height of the standard level*

____
Geopotential height of the standard level (0 10 009) shall be reported in geopotential metres. The standard isobaric level is specified by the preceding entry Pressure (0 07 004).
____

*B/C5.3.5.1* By regional decision, a high-level station which cannot give pressure at mean sea level to a satisfactory degree of accuracy shall report both the station-level pressure and the geopotential height of an agreed standard isobaric surface. [12.2.3.4.2]

*B/C5.4 Basic synoptic “instantaneous” data <3 02 035>*

*B/C5.4.1 Temperature and humidity data <3 02 032>*

*B/C5.4.1.1 Height of sensor above local ground*

____
Height of sensor above local ground (0 07 032) for temperature and humidity measurement shall be reported in metres (with precision in hundredths of a metre).

This datum represents the actual height of temperature and humidity sensors above ground at the point where the sensors are located.
____

*B/C5.4.1.2 Dry-bulb air temperature*

____
Dry-bulb air temperature (0 12 101) shall be reported in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius).

Notes:

{empty}(1) Temperature data shall be reported with precision in hundredths of a degree even if they are measured with the accuracy in tenths of a degree. This requirement is based on the fact that conversion from the Kelvin to the Celsius scale has often resulted into distortion of the data values.

{empty}(2) Temperature t (in degrees Celsius) shall be converted into temperature T (in kelvin) using equation: T = t + 273.15.
____

*B/C5.4.1.2.1* When the data are not available as a result of a temporary instrument failure, this quality shall be included as a missing value. [12.2.3.2]

*B/C5.4.1.3 Dewpoint temperature*

____
Dewpoint temperature (0 12 103) shall be reported in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius).

Note: Notes 1 and 2 under Regulation B/C5.4.1.2 shall apply.
____

*B/C5.4.1.3.1* When the data are not available as a result of a temporary instrument failure, this quality shall be included as a missing value. [12.2.3.3.2]

*B/C5.4.1.4 Relative humidity*

____
Relative humidity (0 13 003) shall be reported in units of a per cent.
____

*B/C5.4.1.4.1* _Both dewpoint temperature and relative humidity shall be reported when available._

*B/C5.4.2 Visibility data <3 02 033>*

*B/C5.4.2.1 Height of sensor above local ground*

____
Height of sensor above local ground (0 07 032) for visibility measurement shall be reported in metres (with precision in hundredths of a metre).

This datum represents the actual height of visibility sensors above ground at the point where the sensors are located. If visibility is estimated by a human observer, average height of observer’s eyes above station ground shall be reported.
____

*B/C5.4.2.2 Horizontal visibility*

____
Horizontal visibility (0 20 *001*) at surface shall be reported in metres (with precision in tens of metres).
____

*B/C5.4.2.2.1* When the horizontal visibility is not the same in different directions, the shortest distance shall be given for visibility. [12.2.1.3.1]

*B/C5.4.2.2.2* Horizontal visibility greater than 81 900 m shall be expressed by 0 20 001 set to 81 900 m; if TDCF data are converted from TAC data, 0 20 001 set to 81 900 m shall indicate horizontal visibility greater than 70 000 m.

*B/C5.4.3 Precipitation past 24 hours <3 02 034>*

*B/C5.4.3.1 Height of sensor above local ground*

____
Height of sensor above local ground (0 07 032) for precipitation measurement shall be reported in metres (with precision in hundredths of a metre).

This datum represents the actual height of the rain gauge rim above ground at the point where the rain gauge is located.
____

*B/C5.4.3.2 Total amount of precipitation during the 24-hour period*

____
Total amount of precipitation during the 24-hour period ending at the time of observation (0 13 023) shall be reported in kilograms per square metre (with precision in tenths of a kilogram per square metre). [12.4.9]
____

*B/C5.4.3.2.1* The precipitation over the past 24 hours shall be included (not missing) at least once a day at one appropriate time of the main standard times (0000, 0600, 1200, 1800 UTC). [12.4.1]

*B/C5.4.3.2.2* Precipitation, when it can be and has to be reported, shall be reported as 0.0 kg m^–2^ if no precipitation were observed during the referenced period. [12.2.5.4]

*B/C5.4.3.2.3* Trace shall be reported as “–0.1 kg m^–2^”.

*B/C5.4.4 General cloud information <3 02 004>*

*B/C5.4.4.1 Total cloud cover*

____
_Total cloud cover (0 20 010) shall embrace the total fraction of the celestial dome covered by clouds irrespective of their genus. It shall be reported_ in _units of a per cent_.

Note: Total cloud cover shall be reported as 113 when sky is obscured by fog and/or other meteorological phenomena.
____

*B/C5.4.4.1.1* Total cloud cover shall be reported as actually seen by the observer during the observation. [12.2.2.2.1]

*B/C5.4.4.1.2* Altocumulus perlucidus or Stratocumulus perlucidus (“mackerel sky”) shall be reported _as 99% or less_ (unless overlying clouds appear to cover the whole sky) since breaks are always present in this cloud form even if it extends over the whole celestial dome. [12.2.2.2.2]

*B/C5.4.4.1.3* Total cloud cover shall be reported as zero when blue sky or stars are seen through existing fog or other analogous phenomena without any trace of cloud being seen. [12.2.2.2.3]

*B/C5.4.4.1.4* When clouds are observed through fog or analogous phenomena, their amount shall be evaluated and reported as if these phenomena were non-existent. [12.2.2.2.4]

*B/C5.4.4.1.5* Total cloud cover shall not include the amount resulting from rapidly dissipating condensation trails. [12.2.2.2.5]

*B/C5.4.4.1.6* Persistent condensation trails and cloud masses which have obviously developed from condensation trails shall be reported as cloud. [12.2.2.2.6]

*B/C5.4.4.2 Vertical significance (surface observations)* – Code table 0 08 002

____
To specify vertical significance (0 08 002) within the sequence 3 02 004, a code figure shall be selected in the following way:

{empty}(a) If low clouds are observed, then code figure 7 (Low cloud) shall be used;

{empty}(b) If there are no low clouds but middle clouds are observed, then code figure 8 (Middle clouds) shall be used;

{empty}(c) If there are no low and there are no middle clouds but high clouds are observed, then code figure 0 shall be used;

{empty}(d) If sky is obscured by fog and/or other phenomena, then code figure 5 (Ceiling) shall be used;

{empty}(e) If there are no clouds (clear sky), then code figure 62 (Value not applicable) shall be used;

{empty}(f) If the cloud cover is not discernible for reasons other than (d) above or observation is not made, then code figure 63 (Missing value) shall be used.
____

*B/C5.4.4.3 Cloud amount (of low or middle clouds*) – Code table 0 20 011

____
_Amount of all the low clouds (clouds of the genera Stratocumulus, Stratus, Cumulus, and Cumulonimbus) present or, if no low clouds are present, the amount of all the middle clouds (clouds of the genera Altocumulus, Altostratus, and Nimbostratus) present_.
____

*B/C5.4.4.3.1* Cloud amount shall be reported as follows:

____
{empty}(a) If there are low clouds, then the total amount of all low clouds, as actually seen by the observer during the observation shall be reported for the cloud amount;

{empty}(b) If there are no low clouds but there are middle clouds, then the total amount of the middle clouds shall be reported for the cloud amount;

{empty}(c) If there are no low clouds and there are no middle clouds but there are high clouds (clouds of the genera Cirrus, Cirrocumulus, and Cirrostratus), then the cloud amount shall be reported as zero;

{empty}[12.2.7.2.1]

*(d) If no clouds are observed (clear sky), then the cloud amount shall be reported as 0;*

*(e) If sky is obscured by fog and/or other meteorological phenomena, then the cloud amount shall be reported as 9;*

*(f) If cloud cover is indiscernible for reasons other than fog or other meteorological phenomena, or observation is not made, the cloud amount shall be reported as missing.*
____

*B/C5.4.4.3.2* Amount of Altocumulus perlucidus or Stratocumulus perlucidus (“mackerel sky”) shall be reported using code figure 7 or less since breaks are always present in this cloud form even if it extends over the whole celestial dome. [12.2.7.2.2]

*B/C5.4.4.3.3* When the clouds reported for cloud amount are observed through fog or an analogous phenomenon, the cloud amount shall be reported as if these phenomena were not present. [12.2.7.2.3]

*B/C5.4.4.3.4* If the clouds reported for cloud amount include contrails, then the cloud amount shall include the amount of persistent contrails. Rapidly dissipating contrails shall not be included in the value for the cloud amount. [12.2.7.2.4]

*B/C5.4.4.4 Height of base of lowest cloud*

____
_Height above surface of the base (0 20 013) of the lowest cloud seen shall be reported_ in metres (with precision in tens of metres).

Note: The term « height above surface » shall be considered as being the height above the official aerodrome elevation or above station elevation at a non-aerodrome station.
____

*B/C5.4.4.4.1* When the station is in fog, a sandstorm or in blowing snow but the sky is discernable, the base of the lowest cloud shall refer to the base of the lowest cloud observed, if any. When, under the above conditions, the sky is not discernible, the base of the lowest cloud shall be replaced by vertical visibility. [12.4.10.5]

*B/C5.4.4.4.2* _When no cloud is reported (total cloud cover = 0)_ the base of the lowest cloud _shall be reported as a missing value._

*B/C5.4.4.4.3* _When, by national decision, clouds with bases below the station are reported from the station and clouds with bases below and tops above the station are observed,_ the base of the lowest cloud _shall be reported having a negative value if the base of cloud is discernible, or as a missing value._

*B/C5.4.4.4.4* _If synoptic data are produced in BUFR or CREX by conversion from a TAC report, the following approach shall be used: Height of base of the lowest cloud 0_ _20_ _013 shall be derived from the h~s~h~s~ in the first group 8 in section 3, i.e. from the h~s~h~s~ of the lowest cloud. If and only if groups 8 are not reported in section 3, 0_ _20_ _013 may be derived from h. The lower limit of the range defined for h~s~h~s~ and for h shall be used. However, if groups 8 are not reported in section 3 and h = 9 and N~h~_ ≠ 0, then 0 _20_ _013 shall be 4_ _000 m; if groups 8 are not reported in section 3 and h = 9 and N~h~ = 0, then 0_ _20_ _013 shall be 8_ _000 m._

*B/C5.4.4.5 Cloud type of low, middle and high clouds* – Code table 0 20 012

____
Clouds of the genera Stratocumulus, Stratus, Cumulus, and Cumulonimbus (low clouds) shall be reported for the first entry 0 20 012, clouds of the genera Altocumulus, Altostratus, and Nimbostratus (middle clouds) shall be reported for the second entry 0 20 012 and clouds of the genera Cirrus, Cirrocumulus, and Cirrostratus (high clouds) shall be reported for the third entry 0 20 012.
____

*B/C5.4.4.5.1* The reporting of type of low, middle and high clouds shall be as specified in the _International Cloud Atlas_ (WMO-No. 407), Volume I. [12.2.7.3]

*B/C5.4.5 Individual cloud layers or masses*

*B/C5.4.5.1 Number of individual cloud layers or masses*

____
The number of individual cloud layers or masses shall be indicated by Delayed descriptor replication factor 0 31 001 in BUFR and by a four-digit number in the Data Section corresponding to the position of the replication descriptor in the Data Description Section of CREX.

Notes:

{empty}(1) The number of cloud layers or masses shall never be set to a missing value.

{empty}(2) The number of cloud layers or masses shall be set to a positive value in a NIL report.

{empty}(3) If data compression is to be used, BUFR Regulation 94.6.3, Note 2, sub-note ix shall apply.
____

*B/C5.4.5.1.1* When reported from a manned station, the number of individual cloud layers or masses shall in the absence of Cumulonimbus clouds not exceed three. Cumulonimbus clouds, when observed, shall always be reported, so that the total number of individual cloud layers or masses can be four. The selection of layers (or masses) to be reported shall be made in accordance with the following criteria:

____
{empty}(a) The lowest individual layer (or mass) of any amount (cloud amount at least one octa or less, but not zero);

{empty}(b) The next higher individual layer (or mass) the amount of which is greater than two octas;

{empty}(c) The next higher individual layer (or mass) the amount of which is greater than four octas;

{empty}(d) Cumulonimbus clouds, whenever observed and not reported under (a), (b) and (c) above.

{empty}[12.4.10.1]
____

*B/C5.4.5.1.2* When the sky is clear, the number of individual cloud layers or masses shall be set to zero.

*B/C5.4.5.1.3* The order of reporting the individual cloud layers or masses shall always be from lower to higher levels. [12.4.10.2]

*B/C5.4.5.2 Individual cloud layer or mass <3 02 005>*

____
Each cloud layer or mass shall be represented by the following four parameters: Vertical significance (0 08 002), amount of individual cloud layer or mass (0 20 011), type of cloud layer or mass (0 20 012) and height of base of individual cloud layer or mass (0 20 013).
____

*B/C5.4.5.2.1 Vertical significance (surface observations)* – Code table 0 08 002

____
To specify vertical significance (0 08 002) within the sequence 3 02 005, a code figure shall be selected in the following way:

{empty}(a) Code figure 1 shall be used in the first non-Cumulonimbus layer;

{empty}(b) Code figure 2 shall be used in the second non-Cumulonimbus layer;

{empty}(c) Code figure 3 shall be used in the third non-Cumulonimbus layer;

{empty}(d) Code figure 4 shall be used in any Cumulonimbus layer;

{empty}(e) If sky is obscured by fog and/or other phenomena, then code figure 5 (Ceiling) shall be used;

{empty}(f) If the cloud cover is not discernible for reasons other than (e) above or observation is not made, then code figure 63 (Missing value) shall be used;

{empty}(g) If a station operates in the automatic mode and is sufficiently equipped, code figure 21, 22, 23 and 24 shall be used to identify the first, the second, the third and the fourth instrument detected cloud layer, respectively;

{empty}(h) If a station operates in the automatic mode and no clouds are detected by the cloud detection system, code figure 20 shall be used.
____

*B/C5.4.5.2.2 Cloud amount, type and height of base*

*B/C5.4.5.2.2.1* When the sky is clear, in accordance with Regulation B/C5.4.5.1.2 cloud amount, genus, and height shall not be included. [12.4.10.4]

*B/C5.4.5.2.2.2* In determining cloud amounts (Code table 0 20 011) to be reported for individual layers or masses, the observer shall estimate, by taking into consideration the evolution of the sky, the cloud amounts of each individual layer or mass at the different levels, as if no other clouds existed. [12.4.10.3]

*B/C5.4.5.2.2.3* Type of a cloud layer or mass (Code table 0 20 012) shall be reported using code figures 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 59 and 63.

*B/C5.4.5.2.2.4* If, notwithstanding the existence of fog, sandstorm, duststorm, blowing snow or other obscuring phenomena, the sky is discernible, the partially obscuring phenomena shall be disregarded. If, under the above conditions, the sky is not discernible, the cloud type shall be reported using _code figure 59_ and the cloud height shall be replaced by vertical visibility.

____
Note: The vertical visibility is defined as the vertical visual range into an obscuring medium.

{empty}[12.4.10.5]
____

*B/C5.4.5.2.2.5* If two or more types of cloud occur with their bases at the same level and this level is one to be reported in accordance with Regulation B/C5.4.5.1.1, the selection for cloud type and amount shall be made with the following criteria:

____
{empty}(a) If these types do not include Cumulonimbus then cloud genus shall refer to the cloud type that represents the greatest amount, or if there are two or more types of cloud all having the same amount, the highest applicable code figure for cloud genus shall be reported. Cloud amount shall refer to the total amount of cloud whose bases are all at the same level;

{empty}(b) If these types do include Cumulonimbus then one layer shall be reported to describe only this type with cloud genus indicated as Cumulonimbus and the cloud amount as the amount of the Cumulonimbus. If the total amount of the remaining type(s) of cloud (excluding Cumulonimbus) whose bases are all at the same level is greater than that required by Regulation B/C5.4.5.1.1, then another layer shall be reported with type being selected in accordance with (a) and amount referring to the total amount of the remaining cloud (excluding Cumulonimbus).

{empty}[12.4.10.6]
____

*B/C5.4.5.2.2.6* Regulations B/C5.4.4.1.3 to B/C5.4.4.1.6, inclusive, shall apply. [12.4.10.7]

*B/C5.4.5.2.2.7* _Height above surface of the cloud base (0 20 013) shall be reported_ in metres (with precision in tens of metres).

____
Note: The term « height above surface » shall be considered as being the height above the official aerodrome elevation or above station elevation at a non-aerodrome station.
____

*B/C5.5 Clouds with bases below station level <3 02 036>*

*B/C5.5.1 Number of cloud layers with bases below station level*

____
The number of cloud layers *with bases below station level* shall be indicated by Delayed descriptor replication factor 0 31 001 in BUFR and by a four-digit number in the Data Section corresponding to the position of the replication descriptor in the Data Description Section of CREX.

Notes:

{empty}(1) The number of cloud layers *with bases below station level* shall never be set to a missing value.

{empty}(2) The number of cloud layers *with bases below station level* shall be set to a positive value in a NIL report.

{empty}(3) If data compression is to be used, BUFR Regulation 94.6.3, Note 2, sub-note ix shall apply.
____

*B/C5.5.1.1* Inclusion of these data shall be determined by national decision. The number of cloud layers with bases below station level shall be always set to zero in reports from a station at which observations of clouds with bases below station level are not executed.

*B/C5.5.1.2* When no cloud layers *with bases below station are observed*, the number of cloud layers *with bases below station level* shall be set to zero.

*B/C5.5.1.3* If the station is in continuous or almost continuous cloud, the number of cloud layers *with bases below station level* shall be set to one, with all parameters reported as missing except for vertical significance 0 08 002 that shall be set to 10 (cloud layer with a base below and tops above station level). [12.5.4]

*B/C5.5.1.4* If clouds with bases below station level are not discernible due to fog and/or other phenomena or observation is not made, then the number of cloud layers *with bases below station level* shall be set to one, with all parameters reported as missing except for vertical significance 0 08 002 that shall be set to 11.

*B/C5.5.1.5* When two or more cloud layers with their bases below station level occur at different levels, two or more cloud layers shall be reported. [12.5.5]

*B/C5.5.1.6* Clouds with bases below and tops above station level shall be reported as the first layer within the _sequence 3 02 036_, provided that the station is out of cloud sufficiently frequently to enable the various features to be recognized. Other low clouds present with tops below station level shall be reported as the following layers (one or more) within the _sequence 3 02 036._ _[12.5.3]_

____
Notes:

{empty}(1) Clouds with bases below and tops above station level shall be reported also in __sequences 3 02 004 and 3 02 005. [__12.5.3]

{empty}(2) Clouds with tops below station level shall be reported only in sequence 3__ __02__ __036, and any co-existent clouds with bases above station level shall be reported only __in sequences 3 02 004 and 3 02 005. [__12.5.2]
____

*B/C5.5.2 Individual cloud layer with base below station level*

____
Each cloud layer *with base below station level* shall be represented by the following five parameters: Vertical significance (0 08 002), amount of _clouds with base below station level_ (0 20 011), type of _clouds with base below station level_ (0 20 012), a__ltitude of the upper surface of clouds (0__ _20 014) and cloud top description (0_ _20 017)._
____

*B/C5.5.2.1 Vertical significance (surface observations)* – Code table 0 08 002

____
Code figure 10 shall be used for cloud layers with bases below and tops above station level; code figure 11 shall be used for cloud layers with bases and tops below station level.
____

*B/C5.5.2.2 Amount of _clouds with base below station level_* – Code table 0 20 011

*B/C5.5.2.2.1* Regulations B/C5.4.4.1.1 to B/C5.4.4.1.6, inclusive, shall apply. [12.5.8]

*B/C5.5.2.2.2* Spaces occupied by mountains emerging from the cloud layers shall be counted as occupied by clouds. [12.5.9]

*B/C5.5.2.3 Type of _clouds with base below station level_* – Code table 0 20 012

____
Type of clouds with bases below station level shall be reported using code figures 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 and 63.
____

*B/C5.5.2.4 Height of top of _clouds_* *above mean sea level*

____
_Height of top of clouds above mean sea level (0 20 014) shall be reported_ in metres (with precision in tens of metres).
____

*B/C5.5.2.4.1* Height of top of clouds with bases below and tops above station level shall be reported, provided that the upper surface of clouds can be observed. [12.5.3 (b)]

*B/C5.5.2.5 Cloud top d__escription __*– Code table 0 20 017

*B/C5.5.2.5.1* Description of top of clouds with bases below and tops above station level shall be reported, provided that the station is out of cloud sufficiently frequently to enable the features to be recognized.

*B/C5.5.2.5.2* Rapidly dissipating condensation trails shall not be reported__.__ However, the top of persistent condensation trails and cloud masses which have obviously developed from condensation trails (and whose bases are below station level) shall be reported in _Sequence 3 02 036_. [12.5.6], [12.5.7]

*B/C5.6 Direction of cloud drift <3 02 047>*

____
This information is required from land stations mainly in the tropics. [12.4.7.5]
____

*B/C5.6.1 Vertical significance (surface observations)* – Code table 0__ __08__ __002

____
To specify vertical significance (0 08 002) within the sequence 3 02 047, code figures shall be selected in the following way:

{empty}(a) Code figure 7 (Low cloud) shall be used in the first replication;

{empty}(b) Code figure 8 (Middle clouds) shall be used in the second replication;

{empty}(c) Code figure 9 (High cloud) shall be used in the third replication.
____

*B/C5.6.2 True direction from which clouds are moving*

____
True direction from which low, middle, or high clouds are moving (0 20 054) shall be reported in degrees true as follows:

{empty}(a) True direction from which the low clouds are moving shall be included in the first replication;

{empty}(b) True direction from which the middle clouds are moving shall be included in the second replication;

{empty}(c) True direction from which the high clouds are moving shall be included in the third replication.
____

*B/C5.7 Direction and elevation of cloud <3 02 048>*

____
This information is required from land stations mainly in the tropics. [12.4.7.5]
____

*B/C5.7.1* *Direction of cloud*

____
True direction (0 05 021), from which orographic clouds or clouds with vertical development are seen, shall be _reported in degrees true_. The cloud genus shall be specified by the third entry of the sequence 3 02 048, i.e. by Cloud type – Code table 0 20 012.

Note: It is considered sufficient to report direction of cloud in degrees true, although 0 05 021 (Bearing or azimuth) is defined with higher accuracy (hundredths of a degree true).
____

*B/C5.7.2 Elevation of cloud*

____
Elevation angle (0 07 021) of the top of the cloud shall be reported in degrees. The cloud genus shall be specified by the following entry, i.e. by Cloud type – Code table 0 20 012.

Note: It is considered sufficient to report elevation of the top of cloud in degrees, although 0 07 021 (Elevation angle) is defined with higher accuracy (hundredths of a degree).
____

*B/C5.8 State of ground, snow depth, ground minimum temperature <3 02 037>*

*B/C5.8.1 State of ground* (with or without snow) – Code table 0 20 062

____
State of ground without snow or with snow shall be reported using Code table 0 20 062. The synoptic hour at which this datum is reported shall be determined by regional decision.
____

*B/C5.8.2 Total snow depth*

____
Total snow depth (0 13 013) shall be reported in metres (with precision in hundredths of a metre). The synoptic hour at which this datum is reported shall be determined by regional decision.
____

*B/C5.8.2.1* When total snow depth has to be reported, it is reported as 0.00 m if no snow, ice and other forms of solid precipitation on the ground are observed at the time of observation. A snow depth value of “–0.01 m” shall indicate a little (less than 0.005 m) snow. A snow depth value of “–0.02 m” shall indicate “snow cover not continuous”.

*B/C5.8.2.2* The measurement shall include snow, ice and all other forms of solid precipitation on the ground at the time of observation. [12.4.6.1]

*B/C5.8.2.3* When the depth is not uniform, the average depth over a representative area shall be reported. [12.4.6.2]

*B/C5.8.3 Ground minimum temperature, past 12 hours*

____
Ground minimum temperature from the previous 12 hours (0 12 113) shall be reported in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius).

Notes:

{empty}(1) Ground minimum temperature data shall be reported with precision in hundredths of a degree even if they are measured with the accuracy in tenths of a degree. Notes 1 and 2 under Regulation B/C5.4.1.2 shall apply.

{empty}(2) The period of time covered by ground minimum temperature and the synoptic hour at which this temperature is reported shall be determined by regional decision. If ground minimum temperature is to be reported from the period of previous night, then “ground minimum temperature, past 12 hours” (0 12 113) shall be reported as a missing value. In this case, ground minimum temperature of the previous night (0 12 122) shall be reported in compliance with Regulation B/C5.9.
____

*B/C5.9 “Instantaneous” data required by regional or national reporting practices*

____
If regional or national reporting practices require inclusion of additional “instantaneous” parameters, the sequence descriptor 3 07 090 shall be supplemented by the required element descriptors being preceded by a relevant time period descriptor set to zero, i.e. 0 04 024 = 0 or 0 04 025 = 0.

Notes:

{empty}(1) “Instantaneous” parameter is a parameter that is not coupled to a time period descriptor, e.g. 0 04 024, 0 04 025.

{empty}(2) No regional requirements are currently indicated for reporting SYNOP MOBIL data in the _Manual on Codes_ (WMO-No. 306), Volume II.
____

*B/C5.10 Basic synoptic “period” data <3 02 043>*

*B/C5.10.1 Present and past weather <3 02 038>*

*B/C5.10.1.1* Present weather (Code table 0 20 003) and past weather (1) (Code table 0 20 004) and past weather (2) (Code table 0 20 005) shall be reported as non-missing values if present and past conditions are known. In case of a report from a manually operated station after a period of closure or at start up, when past weather conditions for the period applicable to the report are unknown, past weather (1) and past weather (2) reported as missing shall indicate that previous conditions are unknown. This regulation shall also apply to automatic reporting stations with the facility to report present and past weather. [12.2.6.1]

*B/C5.10.1.2* Code figures 0, 1, 2, 3, 100, 101, 102 and 103 for present weather and code figures 0, 1, 2 and 10 for past weather (1) and past weather (2) shall be considered to represent phenomena without significance. [12.2.6.2]

*B/C5.10.1.3* Present and past weather shall be _reported if observation was made (data available), regardless significance of the phenomena._

____
_Note: If data are produced and collected in traditional codes and present weather and past weather is omitted in a SYNOP report (no significant phenomena observed), code figure 508 shall be used for present weather and code figure 10 for past weather_ (1) and past weather (2) when converted _into BUFR or CREX._
____

*B/C5.10.1.4* If no observation was made (data not available)_, code figure 509 shall be used for present weather and both past weather_ (1) and past weather (2) _shall be reported as missing._

*B/C5.10.1.5* *Present weather from a manned weather station*

*B/C5.10.1.5.1* If more than one form of weather is observed, the highest applicable code figure from the range <00 to 99> shall be selected for present weather. Code figure 17 shall have precedence over code figures 20–49. Other weather may be reported using additional entries 0 20 003 or 0 20 021 to 0 20 026 applying Regulation B/C5.9. [12.2.6.4.1]

*B/C5.10.1.5.2* In coding 01, 02, or 03, there is no limitation on the magnitude of the change of the cloud amount. Code figures 00, 01, and 02 can each be used when the sky is clear at the time of observation. In this case, the following interpretation of the specifications shall apply:

____
– 00 is used when the preceding conditions are not known;

– 01 is used when the clouds have dissolved during the past hour;

– 02 is used when the sky has been continuously clear during the past hour.

{empty}[12.2.6.4.2]
____

*B/C5.10.1.5.3* When the phenomenon is not predominantly water droplets, the appropriate code figure shall be selected without regard to visibility. [12.2.6.4.3]

*B/C5.10.1.5.4* The code figure 05 shall be used when the obstruction to vision consists predominantly of lithometeors. [12.2.6.4.4]

*B/C5.10.1.5.5* National instructions shall be used to indicate the specifications for code figures 07 and 09. [12.2.6.4.5]

*B/C5.10.1.5.6* The visibility restrictions on code figure 10 shall be 1 000 metres or more. The specification refers only to water droplets and ice crystals. [12.2.6.4.6]

*B/C5.10.1.5.7* For code figures 11 or 12 to be reported, the apparent visibility shall be less than 1000 metres. [12.2.6.4.7]

*B/C5.10.1.5.8* For code figure 18, the following criteria for reporting squalls shall be used:

____
{empty}(a) When wind speed is measured: A sudden increase of wind speed of at least eight metres per second, the speed rising to 11 metres per second or more and lasting for at least one minute;

{empty}(b) When the Beaufort scale is used for estimating wind speed: A sudden increase of wind speed by at least three stages of the Beaufort scale, the speed rising to force 6 or more and lasting for at least one minute.

{empty}[12.2.6.4.8]
____

*B/C5.10.1.5.9* Code figures 20–29 shall never be used when precipitation is observed at the time of observation. [12.2.6.4.9]

*B/C5.10.1.5.10* For code figure 28, visibility shall have been less than 1 000 metres.

____
Note: The specification refers only to visibility restrictions which occurred as a result of water droplets or ice crystals.

{empty}[12.2.6.4.10]
____

*B/C5.10.1.5.11* For synoptic coding purposes, a thunderstorm shall be regarded as being at the station from the time thunder is first heard, whether or not lightning is seen or precipitation is occurring at the station. A thunderstorm shall be reported if thunder is heard within the normal observational period preceding the time of the report. A thunderstorm shall be regarded as having ceased at the time thunder is last heard and the cessation is confirmed if thunder is not heard for 10–15 minutes after this time. [12.2.6.4.11]

*B/C5.10.1.5.12* The necessary uniformity in reporting code figures 36, 37, 38, and 39, which may be desirable within certain regions, shall be obtained by means of national instructions. [12.2.6.4.12]

*B/C5.10.1.5.13* A visibility restriction « less than 1 000 metres » shall be applied to code figures 42–49. In the case of code figures 40 or 41, the apparent visibility in the fog or ice fog patch or bank shall be less than 1 000 metres. Code figures 40–47 shall be used when the obstructions to vision consist predominantly of water droplets or ice crystals, and 48 or 49 when the obstructions consist predominantly of water droplets. [12.2.6.4.13]

*B/C5.10.1.5.14* When referring to precipitation, the phrase « at the station » in the code table shall mean « at the point where the observation is normally taken ». [12.2.6.4.14]

*B/C5.10.1.5.15* The precipitation shall be encoded as intermittent if it has been discontinuous during the preceding hour, without presenting the character of a shower. [12.2.6.4.15]

*B/C5.10.1.5.16* The intensity of precipitation shall be determined by the intensity at the time of the observation. [12.2.6.4.16]

*B/C5.10.1.5.17* Code figures 80–90 shall be used only when the precipitation is of the shower type and takes place at the time of the observation.

____
Note: Showers are produced by convective clouds. They are characterized by their abrupt beginning and end and by the generally rapid and sometimes great variations in the intensity of the precipitation. Drops and solid particles falling in a shower are generally larger than those falling in non-showery precipitation. Between showers openings may be observed unless stratiform clouds fill the intervals between the cumuliform clouds.

{empty}[12.2.6.4.17]
____

*B/C5.10.1.5.18* In reporting code figure 98, the observer shall be allowed considerable latitude in determining whether precipitation is or is not occurring, if it is not actually visible. [12.2.6.4.18]

*B/C5.10.1.6 Present weather from an automatic weather station*

*B/C5.10.1.6.1* The highest applicable code figure shall be selected. [12.2.6.5.1]

*B/C5.10.1.6.2* In coding code figures 101, 102, and 103, there is no limitation on the magnitude of the change of the cloud amount. Code figures 100, 101, and 102 can each be used when the sky is clear at the time of observation. In this case, the following interpretation of the specifications shall apply:

____
– Code figure 100 is used when the preceding conditions are not known;

– Code figure 101 is used when the clouds have dissolved during the past hour;

– Code figure 102 is used when the sky has been continuously clear during the past hour.

{empty}[12.2.6.5.2]
____

*B/C5.10.1.6.3* When the phenomenon is not predominantly water droplets, the appropriate code figure shall be selected without regard to the visibility. [12.2.6.5.3]

*B/C5.10.1.6.4* The code figures 104 and 105 shall be used when the obstruction to vision consists predominantly of lithometeors. [12.2.6.5.4]

*B/C5.10.1.6.5* The visibility restriction on code figure 110 shall be 1 000 metres or more. The specification refers only to water droplets and ice crystals. [12.2.6.5.5]

*B/C5.10.1.6.6* For code figure 118, the following criteria for reporting squalls shall be used:

A sudden increase of wind speed of at least eight metres per second, the speed rising to 11 metres per second or more and lasting for at least one minute.

____
{empty}[12.2.6.5.6]
____

*B/C5.10.1.6.7* Code figures 120–126 shall never be used when precipitation is observed at the time of observation. [12.2.6.5.7]

*B/C5.10.1.6.8* For code figure 120, visibility shall have been less than 1 000 metres.

____
Note: _The_ specification refers only to visibility restrictions, which occurred as a result of water droplets or ice crystals.

{empty}[12.2.6.5.8]
____

*B/C5.10.1.6.9* For synoptic coding purposes, a thunderstorm shall be regarded as being at the station from the time thunder is first detected, whether or not lightning is detected or precipitation is occurring at the station. A thunderstorm shall be reported in present weather if thunder is detected within the normal observational period preceding the time of the report. A thunderstorm shall be regarded as having ceased at the time thunder is last detected and the cessation is confirmed if thunder is not detected for 10–15 minutes after this time. [12.2.6.5.9]

*B/C5.10.1.6.10* A visibility restriction « less than 1 000 metres » shall be applied to code figures 130–135. [12.2.6.5.10]

*B/C5.10.1.6.11* The precipitation shall be encoded as intermittent if it has been discontinuous during the preceding hour, without presenting the character of a shower. [12.2.6.5.11]

*B/C5.10.1.6.12* The intensity of precipitation shall be determined by the intensity at the time of observation. [12.2.6.5.12]

*B/C5.10.1.6.13* Code figures 180–189 shall be used only when the precipitation is intermittent or of the shower type and takes place at the time of observation.

____
Note: Showers are produced by convective clouds. They are characterized by their abrupt beginning and end and by the generally rapid and sometimes great variations in the intensity of the precipitation. Drops and solid particles falling in a shower are generally larger than those falling in non-showery precipitation. Between showers openings may be observed unless stratiform clouds fill the intervals between the cumuliform clouds.

{empty}[12.2.6.5.13]
____

*B/C5.10.1.7 Past weather reported from a manned weather station*

*B/C5.10.1.7.1 Time period*

____
The time period (0 04 024) covered by past weather (1) and past weather (2) shall be expressed as _a negative value_ in hours:

{empty}(a) Six hours, for observations at 0000, 0600, 1200, and 1800 UTC;

{empty}(b) Three hours for observations at 0300, 0900, 1500, and 2100 UTC;

{empty}(c) Two hours for intermediate observations if taken every two hours;

{empty}(d) _One hour for intermediate observations if taken every hour_.

{empty}[12.2.6.6.1]
____

*B/C5.10.1.7.2* The code figures for past weather (1) and past weather (2) shall be selected in such a way that past and present weather together give as complete a description as possible of the weather in the time interval concerned. For example, if the type of weather undergoes a complete change during the time interval concerned, the code figures selected for past weather (1) and past weather (2) shall describe the weather prevailing before the type of weather indicated by present weather began. [12.2.6.6.2]

*B/C5.10.1.7.3* When the past weather (1) and past weather (2) are used in hourly reports, Regulation B/C5.10.1.7.1 (d) shall apply. [12.2.6.6.3]

*B/C5.10.1.7.4* If, using Regulation B/C5.10.1.7.2, more than one code figure may be given to past weather (1), the highest figure shall be reported for past weather (1) and the second highest code figure shall be reported for past weather (2). [12.2.6.6.4]

*B/C5.10.1.7.5* If the weather during the period has not changed so that only one code figure may be selected for past weather, then that code figure shall be reported for both past weather (1) and past weather (2). [12.2.6.6.5]

*B/C5.10.1.8 Past weather reported from an automatic weather station*

*B/C5.10.1.8.1 Time period*

____
The time period (0 04 024) covered by past weather (1) and past weather (2) shall be expressed as _a negative value_ in hours:

{empty}(a) Six hours for observations at 0000, 0600, 1200, and 1800 UTC;

{empty}(b) Three hours for observations at 0300, 0900, 1500, and 2100 UTC;

{empty}(c) Two hours for intermediate observations if taken every two hours;

{empty}(d) _One hour for intermediate observations if taken every hour_.

{empty}[12.2.6.7.1]
____

*B/C5.10.1.8.2* The code figures for past weather (1) and past weather (2) shall be selected so that the maximum capability of the automatic station to discern past weather is utilized, and so that past and present weather together give as complete a description as possible of the weather in the time interval concerned. [12.2.6.7.2]

*B/C5.10.1.8.3* In cases where the automatic station is capable only of discerning very basic weather conditions, the lower code figures representing basic and generic phenomena may be used. If the automatic station has higher discrimination capabilities, the higher code figures representing more detailed explanation of the phenomena shall be used. For each basic type of phenomenon, the highest code figure within the discrimination capability of the automatic station shall be reported. [12.2.6.7.3]

*B/C5.10.1.8.4* If the type of weather during the time interval concerned undergoes complete and discernible changes, the code figures selected for past weather (1) and past weather (2) shall describe the weather prevailing before the type of weather indicated by present weather began. The highest figure shall be reported for past weather (1) and the second highest code figure shall be reported for past weather (2). [12.2.6.7.4]

*B/C5.10.1.8.5* If a discernible change in weather has not occurred during the period, so that only one code figure may be selected for the past weather, then that code figure shall be reported for both past weather (1) and past weather (2). For example, rain during the entire period shall be reported as code figure 14 for both past weather (1) and past weather (2) in the case of an automatic station incapable of differentiating types of precipitation, or code figure 16 for both past weather (1) and past weather (2) in the case of a station with the higher discrimination capability. [12.2.6.7.5]

*B/C5.10.2 Sunshine data (from 1 hour and 24-hour period) <1 01 002><3 02 039>*

*B/C5.10.2.1 Period of reference for sunshine duration*

____
Time period in hours (0 04 024) shall be included as follows:

{empty}(a) one hour in the first replication (reported as –1);

{empty}(b) 24 hours in the second replication (reported as –24).
____

*B/C5.10.2.2 Duration of sunshine*

____
Duration of sunshine from the time period specified by the preceding parameter 0 04 024, shall be reported in minutes.
____

*B/C5.10.2.2.1* The duration of sunshine over the previous hour shall be reported by national decision. When reported, it shall be included in the first replication.

*B/C5.10.2.2.2* The duration of sunshine over the previous 24 hours shall, by regional decision, be reported at all stations capable of doing so and included at either 0000 UTC, 0600 UTC, 1200 UTC or 1800 UTC. When reported, it shall be included in the second replication. [12.4.7.4.2]

* +
*

*B/C5.10.3 Precipitation measurement <3 02 040>*

*B/C5.10.3.1 Height of sensor above local ground*

____
Height of sensor above local ground (0 07 032) for precipitation measurement shall be reported in metres (with precision in hundredths of a metre).

This datum represents the actual height of the rain gauge rim above ground at the point where the rain gauge is located.
____

*B/C5.10.3.2 Period of reference for amount of precipitation*

____
Time period (0 04 024) for amount of precipitation shall be reported as _a negative value_ in hours. It shall be determined:

{empty}(a) By regional decision (e.g. –6, –12, –24) in the first replication;

{empty}(b) By national decision (e.g. –1, –3) in the second replication.
____

*B/C5.10.3.3 Total amount of precipitation*

____
Total amount of precipitation, which has fallen during the period of reference for amount of precipitation, shall be reported in kilograms per square metre (with precision in tenths of a kilogram per square metre).
____

*B/C5.10.3.3.1* Precipitation, when it can be and has to be reported, shall be reported as 0.0 kg m^–2^ if no precipitation were observed during *the* referenced period. [12.2.5.4]

*B/C5.10.3.3.2* Trace shall be reported as “–0.1 kg m^–2^”.

*B/C5.10.4 Extreme temperature data <3 02 041>*

*B/C5.10.4.1 Height of sensor above local ground*

____
Height of sensor above local ground (0 07 032) for temperature measurement shall be reported in metres (with precision in hundredths of a metre).

This datum represents the actual height of temperature sensor(s) above ground at the point where the sensors are located.
____

*B/C5.10.4.2 Periods of reference for extreme temperatures*

____
Time period for maximum temperature and time period for minimum temperature (0 04 024) shall be determined by regional decision and reported as _negative values_ in hours. [12.4.4]

Notes:

{empty}(1) If the period for maximum temperature or the period for minimum temperature ends at the nominal time of report, the second value of 0 04 024 shall be reported as 0.

{empty}(2) If the period for maximum temperature or the period for minimum temperature does not end at the nominal time of report, the first value of 0 04 024 shall indicate the beginning of the period of reference and the second value of 0 04 024 shall indicate the end of the period of reference. E.g. to report the maximum temperature for the previous calendar day from a station in RA IV, value of the first 0 04 024 shall be set to –30 and value of the second 0 04 024 shall be set to –6, provided that the nominal time of the report 12 UTC corresponds to 6 a.m. local time.
____

*B/C5.10.4.3 Maximum and minimum temperature*

____
Maximum and minimum temperature shall be reported in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius).

Note: Notes 1 and 2 under Regulation B/C5.4.1.2 shall apply.
____

*B/C5.10.5 Wind data <3 02 042>*

*B/C5.10.5.1 Height of sensor above local ground*

____
Height of sensor above local ground (0 07 032) for wind measurement shall be reported in metres (with precision in hundredths of a metre).

This datum represents the actual height of the sensors above ground at the point where the sensors are located.
____

*B/C5.10.5.2 Type of instrumentation for wind measurement* – Flag table 0 02 002

____
This datum shall be used to specify whether the wind speed was measured by certified instruments (bit No. 1 set to 1) or estimated on the basis of the Beaufort wind scale (bit No. 1 set to 0), and to indicate the original units for wind speed measurement. Bit No. 2 set to 1 indicates that wind speed was originally measured in knots and bit No. 3 set to 1 indicates that wind speed was originally measured in kilometres per hour. Setting both bits No. 2 and No. 3 to 0 indicates that wind speed was originally measured in metres per second.
____

*B/C5.10.5.3 Wind direction* *and speed*

____
The mean direction and speed of the wind over the 10-minute period immediately preceding the observation shall be reported. The time period (0 04 025) shall be included as –10. However, when the 10-minute period includes a discontinuity in the wind characteristics, only data obtained after the discontinuity shall be used for reporting the mean values, and hence the period (0 04 025) in these circumstances shall be correspondingly reduced. [12.2.2.3.1]

The time period is preceded by a time significance qualifier (0 08 021) that shall be set to 2 (Time averaged).

The wind direction (0 11 001) shall be reported in degrees true and the wind speed (0 11 002) shall be reported in metres per second (with precision in tenths of a metre per second).

Note: Surface wind direction measured at a station within 1° of the North Pole or within 1° of the South Pole shall be reported in such a way that the azimuth ring shall be aligned with its zero coinciding with the Greenwich 0° meridian.
____

*B/C5.10.5.3.1* In the absence of wind instruments, the wind speed shall be estimated on the basis of the Beaufort wind scale. The Beaufort number obtained by estimation is converted into metres per second by use of the relevant wind speed equivalent column on the Beaufort scale, and this speed is reported for wind speed. [12.2.2.3.2]

*B/C5.10.5.3.2* Calm shall be reported by setting wind direction to 0 and wind speed to 0. Variable shall be reported by setting wind direction to 0 and wind speed to a positive _non-missing_ value.

*B/C5.10.5.4 Maximum wind gust direction and speed*

____
Time period for maximum wind gust direction and speed (0 04 025) shall be determined by regional or national decision and reported as a negative value in minutes.

Direction of the maximum wind gust (0 11 043) shall be reported in degrees true and speed of the maximum wind gust (0 11 041) shall be reported in metres per second (with precision in tenths of a metre per second).
____

* +
*

*B/C5.11 Evaporation data <3 02 044>*

*B/C5.11.1 Period of reference for evaporation data*

____
Evaporation or evapotranspiration during the previous 24 hours shall be reported. Time period in hours (0 04 024) shall be included as –24.
____

*B/C5.11.2 Indicator of type of instrument for evaporation measurement or the type of crops –* Code table 0 02 004

*B/C5.11.3 Evaporation or evapotranspiration*

____
Amount of either evaporation or evapotranspiration (0 13 033) shall be reported in kilograms per square metre (with precision in tenths of a kilogram per square metre) at 0000 UTC, 0600 UTC or 1200 UTC. [12.4.7.2.2]
____

*B/C5.12 Radiation data (from 1 hour and 24-hour period) <1 01 002><3 02 045>*

*B/C5.12.1 Period of reference for radiation data*

____
Radiation integrated over the previous hour and over the previous 24 hours may be reported. Time period in hours (0 04 024) shall be included as follows:

{empty}(a) one hour in the first replication (reported as **–**1);

{empty}(b) 24 hours in the second replication (reported as **–**24).
____

*B/C5.12.2 Amount of radiation*

____
*If included, amount of radiation integrated over the time period specified by the preceding parameter 0 04 024 shall be reported in joules per square metre (with precision in thousands of a joule per square metre for radiation type (a) and (b); with precision in ten-thousands of a joule per square metre for radiation type (c); with precision in hundreds of a joule per square metre for radiation types (d) to (f)).*
____

*B/C5.12.2.1* The radiation data may take one or more of the following forms:

____
{empty}(a) Long-wave radiation (0 14 002); the positive sign shall be used to specify downward long-wave radiation and the negative sign to specify upward long-wave radiation;

{empty}(b) Short-wave radiation (0 14 004);

{empty}(c) Net radiation (0 14 016); the corresponding sign shall be used to specify positive and negative net radiation);

{empty}(d) Global solar radiation (0 14 028);

{empty}(e) Diffuse solar radiation (0 14 029);

{empty}(f) Direct solar radiation (0 14 030).

*[12.4.7.4.3], [12.4.7.4.4]*

Note: Data width and/or reference value of radiation descriptors were changed with introduction of the Version number 14 of WMO FM 94 BUFR Tables.
____

*B/C5.13 Temperature change <3 02 046>*

____
This information is required by regional or national decision from islands or other widely separated stations.
____

*B/C5.13.1 Period of reference for temperature change*

____
The temperature change shall be reported for the period of time between the time of the observation and the time of the occurrence of temperature change. To construct the required period, time period 0 04 024 shall be included twice; the first one corresponding to period covered by past weather (1) and past weather (2), the second one specified by the time of the occurrence of temperature change. Both values of 0 04 024 shall be negative and expressed in hours.

Note: The period is the number of whole hours, disregarding the minutes. For example, if the time of occurrence is 45 minutes after the time of the observation, the time period is considered to be zero hours. If the time of occurrence is 1 hour or more, but less than 2 hours after the observation, the time period go shall be considered to be 1 hour, etc.
____

*B/C5.13.2 Temperature change over period specified*

____
Temperature change (0 12 049) shall be reported in kelvin in BUFR, in degrees Celsius in CREX.
____

*B/C5.13.2.1* For a change of temperature to be reported, the change shall be equal to or more than 5^o^C and occur in less than 30 minutes during the period covered by past weather (1) and past weather (2). [12.4.7.3]

*B/C5.14 “Period” data required by regional or national reporting practices*

____
If regional or national reporting practices require inclusion of additional “period” parameters, the common sequence 3 07 090 shall be supplemented by relevant descriptors.

Notes:

{empty}(1) “Period” parameter is a parameter that is coupled to a time period descriptor, e.g. 0 04 024, 0 04 025.

{empty}(2) No regional requirements are currently indicated for reporting SYNOP MOBIL data in the _Manual on Codes_ (WMO-No. 306), Volume II.
____

_____________
