*B/C30 – Regulations for reporting CLIMAT data in TDCF*

*TM 307073 – BUFR template for reports of monthly values from a land station suitable for CLIMAT data*

[cols=",,",]
|===
| | |*Representation of CLIMAT data of the actual month and for monthly normals*
|*3 07 073* |*3 07 071* |Monthly values from a land station
| |*3 07 072* |Monthly normals for a land station
|===

[cols=",,,,",]
|===
| |Unit, scale | | |
a|
*Monthly values of a land station (data of CLIMAT Sections 0, 1, 3 and 4)*

Sequence BUFR descriptor *<3 07 071>* expands as shown in the leftmost column below.

| | | |
| | | |*Surface station identification; time, horizontal and vertical coordinates* |
| | | |_Surface station identification_ |
|*3 01 090* |3 01 004 |0 01 001 |WMO block number |Numeric, 0
| | |0 01 002 |WMO station number |Numeric, 0
| | |0 01 015 |Station or site name |CCITT IA5, 0
| | |0 02 001 |Type of station |Code table, 0
| |3 01 011 |0 04 001 |Year (see Note 1) |Year, 0
| | |0 04 002 |Month (see Note 1) |Month, 0
| | |0 04 003 |Day (= 1) (see Note 1) |Day, 0
| |3 01 012 |0 04 004 |Hour (= 0) (see Note 1) |Hour, 0
| | |0 04 005 |Minute (= 0) (see Note 1) |Minute, 0
| |3 01 021 |0 05 001 |Latitude (high accuracy) |Degree, 5
| | |0 06 001 |Longitude (high accuracy) |Degree, 5
| |0 07 030 | |Height of station ground above mean sea level |m, 1
| |0 07 031 | |Height of barometer above mean sea level |m, 1
| | | |*Monthly mean values of pressure, temperature, extreme temperatures and vapour pressure* |
|*0 04 074* | | |Short time period or displacement (= UTC – LT) (see Note 1) |Hour, 0
|*0 04 023* | | |Time period or displacement (= number of days in the month) |Day, 0
|*0 08 023* | | |First-order statistics (= 4; mean value) |Code table, 0
|*0 10 004* | | a|
Pressure ________

P~0~P~0~P~0~P~0~

|Pa, –1
|*0 10 051* | | a|
Pressure reduced to mean sea level _____

PPPP

|Pa, –1
|*0 07 004* | | |Pressure (standard level) (for lowland stations +
= missing value) |Pa, –1
|*0 10 009* | | a|
Geopotential height (of the standard level) +
(for lowland stations = missing value) _____

PPPP

|gpm, 0
|*0 07 032* | | |Height of sensor above local ground (or deck of marine platform) (see Note 2) |m, 2
|*0 12 101* | | a|
Temperature/air temperature ____

s~n~TTT

|K, 2
|*0 02 051* | | |Indicator to specify observing method for extreme temperatures (see Note 2) i~y~ |Code table, 0
|*0 04 051* | | |Principal time of daily reading of maximum temperature G~x~G~x~ |Hour, 0
|*0 12 118* | | |Maximum temperature at height specified, past 24 hours s~n~T~x~T~x~T~x~ |K, 2
|*0 04 052* | | |Principal time of daily reading of minimum temperature G~n~G~n~ |Hour, 0
|*0 12 119* | | |Minimum temperature at height specified, past 24 hours s~n~T~n~T~n~T~n~ |K, 2
|*0 13 004* | | a|
Vapour pressure ___

eee

|Pa, –1
|*0 08 023* | | |First-order statistics (set to missing to cancel the previous value) |Code table, 0
|*0 12 151* | | a|
Standard deviation of daily mean temperature

s~t~s~t~s~t~

|K, 2
|*0 07 032* | | a|
====== Height of sensor above local ground (or deck of marine platform) +
(set to missing to cancel the previous value)

|m, 2
| | | |*Number of days in the month for which values are missing* |
|*1 02 005* | | |Replicate 2 descriptors 5 times |
|*0 08 050* | | a|
Qualifier for number of missing values in calculation of statistic

(= 1; pressure)

(= 2; temperature)

(= 4; vapour pressure)

(= 7; maximum temperature)

(= 8; minimum temperature)

|Code table, 0
|*0 08 020* | | a|
Total number of missing entities (with respect to accumulation or average) (days)

m~p~m~p~ (for pressure)

m~T~m~T~ (for temperature)

m~e~m~e~ (for vapour pressure)

m~Tx~ (for maximum temperature)

m~Tn~ (for minimum temperature)

|Numeric, 0
| | | |*Monthly duration of sunshine* |
|*0 14 032* | | |Total sunshine S~1~S~1~S~1~ |Hour, 0
|*0 14 033* | | |Total sunshine p~s~p~s~p~s~ |%, 0
|*0 08 050* | | |Qualifier for number of missing values in calculation of statistic (= 6; sunshine duration) |Code table, 0
|*0 08 020* | | |Total number of missing entities (with respect to accumulation or average) (days) m~S~m~S~ |Numeric, 0
| | | |*Number of days with parameters beyond certain thresholds; number of days with thunderstorm and hail* |
|*1 02 018* | | |Replicate 2 descriptors 18 times |
|*0 08 052* | | a|
Condition for which number of days of occurrence follows

(= 0; wind ≥ 10 m s^–1^)

(= 1; wind ≥ 20 m s^–1^)

(= 2; wind ≥ 30 m s^–1^)

(= 3; max. T <273.15 K)

(= 4; max. T ≥ 298.15 K)

(= 5; max. T ≥ 303.15 K)

(= 6; max. T ≥ 308.15 K)

(= 7; max. T ≥ 313.15 K)

(= 8; min. T < 273.15 K)

(= 16; sss > 0.00 m)

(= 17; sss > 0.01 m)

(= 18; sss > 0.10 m)

(= 19; sss > 0.50 m )

(= 20; horizontal visibility < 50 m)

(= 21; horizontal visibility < 100 m)

(= 22; horizontal visibility < 1000 m)

(= 23; hail)

(= 24; thunderstorm)

|Code table, 0
|*0 08 022* | | a|
Total number (with respect to accumulation or average) (of days)

f~10~f~10~ (wind ≥ 10 m s^–1^)

f~20~f~20~ (wind ≥ 20 m s^–1^)

f~30~f~30~ (wind ≥ 30 m s^–1^)

T~x0~T~x0~ (T~x~ < 273.15 K)

T~25~T~25~ (T~x~ ≥ 298.15 K)

T~30~T~30~ (T~x~ ≥ 303.15 K)

T~35~T~35~ (T~x~ ≥ 308.15 K)

T~40~T~40~ (T~x~ ≥ 313.15 K)

T~n0~T~n0~ (T~n~ < 273.15 K)

s~0~s~0~ (sss > 0.00 m)

s~1~s~1~ (sss > 0.01 m)

s~10~s~10~ (sss > 0.10 m)

s~50~s~50~ (sss > 0.50 m)

V~1~V~1~ (h. viz. < 50 m)

V~2~V~2~ (h. viz. < 100 m)

V~3~V~3~ (h. viz. < 1000 m)

D~gr~D~gr~ (hail)

D~ts~D~ts~ (thunderstorm)

|Numeric, 0
| | | |*Occurrence of extreme values of temperature and wind speed* |
|*0 07 032* | | |Height of sensor above local ground (or deck of marine platform) |m, 2
|*0 08 053* | | a|
Day of occurrence qualifier (= 0; on 1 day only)

(= 1; on 2 or more days)

|Code table, 0
|*0 04 003* | | |Day y~x~y~x~ |Day, 0
|*0 12 152* | | |Highest daily mean temperature s~n~T~xd~T~xd~T~xd~ |K, 2
|*0 08 053* | | a|
Day of occurrence qualifier (= 0; on 1 day only)

(= 1; on 2 or more days)

|Code table, 0
|*0 04 003* | | |Day y~n~y~n~ |Day, 0
|*0 12 153* | | |Lowest daily mean temperature s~n~T~nd~T~nd~T~nd~ |K, 2
|*0 08 053* | | a|
Day of occurrence qualifier (= 0; on 1 day only)

(= 1; on 2 or more days)

|Code table, 0
|*0 04 003* | | |Day y~ax~y~ax~ |Day, 0
|*0 08 023* | | |First-order statistics (= 2; maximum value) |Code table, 0
|*0 12 101* | | |Temperature/air temperature s~n~T~ax~T~ax~T~ax~ |K, 2
|*0 08 053* | | a|
Day of occurrence qualifier (= 0; on 1 day only)

(= 1; on 2 or more days)

|Code table, 0
|*0 04 003* | | |Day y~an~y~an~ |Day, 0
|*0 08 023* | | |First-order statistics (= 3; minimum value) |Code table, 0
|*0 12 101* | | |Temperature/air temperature s~n~T~an~T~an~T~an~ |K, 2
|*0 08 023* | | |First-order statistics (set to missing to cancel the previous value) |Code table, 0
|*0 07 032* | | |Height of sensor above local ground (or deck of marine platform) |m, 2
|*0 02 002* | | |Type of instrumentation for wind measurement |Flag table, 0
|*0 08 053* | | a|
Day of occurrence qualifier (= 0; on 1 day only)

(= 1; on 2 or more days)

|Code table, 0
|*0 04 003* | | |Day y~fx~y~fx~ |Day, 0
|*0 11 046* | | |Maximum instantaneous wind speed f~x~f~x~f~x~ |m s^–1^, 1
|*0 08 053* | | |Day of occurrence qualifier (set to missing to cancel the previous value) |Code table, 0
| | | |*Monthly precipitation data* |
|*0 04 003* | | |Day (= 1) (see Note 3) |Day, 0
|*0 04 004* | | |Hour (= 6) (see Note 3) |Hour, 0
|*0 04 023* | | |Time period or displacement (= number of days in the month) (see Note 3) |Day, 0
|*0 07 032* | | |Height of sensor above local ground (or deck of marine platform) (see Note 2) |m, 2
|*0 13 060* | | |Total accumulated precipitation R~1~R~1~R~1~R~1~ |kg m^–2^, 1
|*0 13 051* | | |Frequency group, precipitation R~d~ |Code table, 0
|*0 04 053* | | |Number of days with precipitation equal to or more than 1 mm n~r~n~r~ |Numeric, 0
|*0 08 050* | | |Qualifier for number of missing values in calculation of statistic (= 5; precipitation) |Code table, 0
|*0 08 020* | | a|
Total number of missing entities (with respect to accumulation or average) (days)

m~R~m~R~ (for precipitation)

|Numeric, 0
| | | |*Number of days with precipitation beyond certain thresholds* |
|*1 02 006* | | |Replicate 2 descriptors 6 times |
|*0 08 052* | | a|
Condition for which number of days of occurrence follows

(= 10; precipitation ≥ 1.0 kg m^–2^)

(= 11; precipitation ≥ 5.0 kg m^–2^)

(= 12; precipitation ≥ 10.0 kg m^–2^)

(= 13; precipitation ≥ 50.0 kg m^–2^)

(= 14; precipitation ≥ 100.0 kg m^–2^)

(= 15; precipitation ≥ 150.0 kg m^–2^)

|Code table, 0
|*0 08 022* | | a|
Total number (with respect to accumulation or average (of days)

R~1~R~1~ (precipitation ≥ 1.0 kg m^–2^)

R~5~R~5~ (precipitation ≥ 5.0 kg m^–2^)

R~10~R~10~ (precipitation ≥ 10.0 kg m^–2^)

R~50~R~50~ (precipitation ≥ 50.0 kg m^–2^)

R~100~R~100~ (precipitation ≥ 100.0 kg m^–2^)

R~150~R~150~ (precipitation ≥ 150.0 kg m^–2^)

|Numeric, 0
| | | |*Occurrence of extreme precipitation* |
|*0 08 053* | | a|
Day of occurrence qualifier (= 0; on 1 day only)

(= 1; on 2 or more days)

|Code table, 0
|*0 04 003* | | |Day y~r~y~r~ |Day, 0
|*0 13 052* | | |Highest daily amount of precipitation R~x~R~x~R~x~ |kg m^–2^, 1
|*0 07 032* | | a|
Height of sensor above local ground (or deck of marine platform)

(set to missing to cancel the previous value)

|m, 2
a|
*Monthly normals for a land station (data of CLIMAT Section 2)*

Sequence BUFR descriptor *<3 07 072>* expands as shown in the leftmost column below.

| | | |
| | | |*Normals of pressure, temperatures, vapour pressure, standard deviation of daily mean temperature, and sunshine duration* |
|*0 04 001* | | |Year (of beginning of the reference period) |Year, 0
|*0 04 001* | | |Year (of ending of the reference period) |Year, 0
|*0 04 002* | | |Month |Month, 0
|*0 04 003* | | |Day (= 1) (see Note 1) |Day, 0
|*0 04 004* | | |Hour (= 0) (see Note 1) |Hour, 0
|*0 04 074* | | |Short time period or displacement (= UTC – LT) (see Note 1) |Hour, 0
|*0 04 022* | | |Time period or displacement (= 1) |Month, 0
|*0 08 023* | | |First-order statistics (= 4; mean value) |Code table, 0
|*0 10 004* | | a|
Pressure ________

P~0~P~0~P~0~P~0~

|Pa, –1
|*0 10 051* | | a|
Pressure reduced to mean sea level _____

PPPP

|Pa, –1
|*0 07 004* | | |Pressure (standard level) |Pa, –1
|*0 10 009* | | a|
Geopotential height (of the standard level)

_____

PPPP

|gpm, 0
|*0 07 032* | | |Height of sensor above local ground (or deck of marine platform) (see Note 2) |m, 2
|*0 12 101* | | a|
Temperature/air temperature ____

s~n~TTT

|K, 2
|*0 02 051* | | |Indicator to specify observing method for extreme temperatures (see Note 2) i~y~ |Code table, 0
|*0 04 051* | | |Principal time of daily reading of maximum temperature G~x~G~x~ |Hour, 0
|*0 12 118* | | a|
Maximum temperature at height specified, past 24 h ______

s~n~T~x~T~x~T~x~

|K, 2
|*0 04 052* | | |Principal time of daily reading of minimum temperature G~n~G~n~ |Hour, 0
|*0 12 119* | | a|
Minimum temperature at height specified, past 24 h ______

s~n~T~n~T~n~T~n~

|K, 2
|*0 13 004* | | a|
Vapour pressure ___

eee

|Pa, –1
|*0 12 151* | | a|
Standard deviation of daily mean temperature

s~t~s~t~s~t~

|K, 2
|*0 07 032* | | |Height of sensor above local ground (or deck of marine platform) (set to missing to cancel the previous value) |m, 2
|*0 14 032* | | |Total sunshine S~1~S~1~S~1~ |Hour, 0
|*0 08 023* | | |First-order statistics (set to missing to cancel the previous value) |Code table, 0
| | | |*Normals of precipitation* |
|*0 04 001* | | |Year (of beginning of the reference period) |Year, 0
|*0 04 001* | | |Year (of ending of the reference period) |Year, 0
|*0 04 002* | | |Month |Month, 0
|*0 04 003* | | |Day (= 1) (see Note 3) |Day, 0
|*0 04 004* | | |Hour (= 6) (see Note 3) |Hour, 0
|*0 04 022* | | |Time period or displacement (= 1) |Month, 0
|*0 07 032* | | |Height of sensor above local ground (or deck of marine platform) (see Note 2) |m, 2
|*0 08 023* | | |First-order statistics (= 4; mean value) |Code table, 0
|*0 13 060* | | |Total accumulated precipitation R~1~R~1~R~1~R~1~ |kg m^–2^, 1
|*0 04 053* | | |Number of days with precipitation equal to or more than 1 mm n~r~n~r~ |Numeric, 0
|*0 08 023* | | |First-order statistics (set to missing to cancel the previous value) |Code table, 0
| | | |*Number of missing years* |
|*1 02 008* | | |Replicate 2 descriptors 8 times |
|*0 08 050* | | a|
Qualifier for number of missing values in calculation of statistic

(= 1; pressure)

(= 2; temperature)

(= 3; extreme temperatures) (see Note 4)

(= 4; vapour pressure)

(= 5; precipitation)

(= 6; sunshine duration)

(= 7; maximum temper**ature)** (see Note 4)

(= 8; minimum temperature) (see Note 4)

|Code table, 0
|*0 08 020* | | a|
Total number of missing entities (with respect to accumulation or average) (years)

y~P~y~P~ (for pressure)

y~T~y~T~ (for temperature)

y~Tx~y~Tx~ (for extreme temperatures) +
(see Note 4)

y~e~y~e~ (for vapour pressure)

y~R~y~R~ (for precipitation)

y~S~y~S~ (for sunshine duration)

for maximum temperature (see Note 4) +
for minimum temperature (see Note 4)

|Numeric, 0
|===

Notes:

{empty}(1) The time identification refers to the beginning of the one-month period. Except for precipitation measurements, the one-month period is recommended to correspond to the local time (LT) month.

{empty}(2) If the height of the sensor or observing method for extreme temperatures was changed during the period specified, the value shall be that which existed for the greater part of the period.

{empty}(3) In case of precipitation measurements, the one-month period begins at 06 UTC on the first day of the month and ends at 06 UTC on the first day of the following month.

{empty}(4) The number of missing years within the reference period from the calculation of normal for mean extreme air temperature should be given, if available, for both the calculation of normal maximum temperature and for the calculation of normal minimum temperature in addition to the number of missing years for the extreme air temperatures reported under 0 08 020 preceded by 0 08 050 in which the figure 3 is used.

* +
Regulations:*

*B/C30.1 Section 1 of BUFR or CREX*

*B/C30.2* Monthly values of a land station

**B/C30.2.1 Surface station identification; time, h**orizontal and vertical coordinates

*B/C30.2.2* Monthly mean values of pressure, temperature, extreme temperatures and vapour pressure; standard deviation of daily mean temperature

B/C30.2.3 *Monthly duration of sunshine*

B/C30.2.4 Number of days with parameters beyond certain thresholds; number of days with thunderstorm and hail

B/C30.2.5 *Occurrence of extreme values of temperature and wind speed*

B/C30.2.6 Monthly precipitation data

B/C30.2.7 Number of days with precipitation beyond certain thresholds

B/C30.2.8 *Occurrence of extreme precipitation*

*B/C30.3* Monthly normals for a land station

*B/C30.3.1* Normals of pressure, temperatures, vapour pressure, standard deviation of daily mean temperature, and sunshine duration

*B/C30.3.2* Normals of precipitation

*B/C30.3.3* Number of missing years

*B/C30.4 Regional or national reporting practices*

*B/C30.1 Section 1 of BUFR or CREX*

*B/C30.1.1 Entries required in Section 1 of BUFR*

____
*The following entries shall be included in BUFR Section 1:*

– *BUFR master table;*

– *Identification of originating/generating centre;*

– *Identification of originating/generating sub-centre;*

– *Update sequence number;*

– *Identification of inclusion of optional section;*

– *Data category (= 000 for CLIMAT data);*

– *International data sub-category (see Notes 1 and 2);*

– *Local data sub-category;*

– *Version number of master table;*

– *Version number of local tables;*

– *Year (year of the century up to BUFR edition 3) (see Note 3);*

– *Month (for which the monthly values are reported) (see Note 3);*

– *Day (= 1*) *(see Note 3);*

– *Hour (= 0*) *(see Note 3)*;

– *Minute (= 0) (see Note 3);*

– *Second (= 0) (see Notes 1 and 3).*

*Notes:*

*(1) Inclusion of this entry is required starting with BUFR edition 4.*

*(2) If required, the international data sub-category shall be included for CLIMAT data as 020.*

{empty}(3) The time identification refers to the beginning of the month *for which the monthly mean values are reported*.

*(4) If an NMHS performs conversion of CLIMAT data produced by another NMHS,* originating centre in Section 1 shall indicate **the converting centre and o**riginating sub-centre shall indicate the *producer of CLIMAT bulletins. Producer of CLIMAT bulletins shall be specified in Common Code table C-12 as a sub-centre of the originating centre, i.e. of the NMHS executing the conversion.*
____

* +
*

*B/C30.1.2 Entries required in Section 1 of CREX*

____
*The following entries shall be included in CREX Section 1:*

– *CREX master table;*

– *CREX edition number;*

– *CREX table version number;*

– *Version number of BUFR master table (see Note 1);*

– *Version number of local tables (see Note 1);*

– *Data category (= 000 for CLIMAT data);*

– *International data sub-category (see Notes 1 and 2);*

– *Identification of originating/generating centre (see Note 1);*

– *Identification of originating/generating sub-centre (see Note 1);*

– *Update sequence number (see Note 1);*

– *Number of subsets (see Note 1);*

– *Year (see Notes 1 and 3);*

– *Month (for which the monthly values are reported) (see Notes 1 and 3);*

– *Day (= 1*) *(see Notes 1 and 3);*

– *Hour (= 0*) *(see Notes 1 and 3)*;

– *Minute (= 0) (see Notes 1 and 3).*

*Notes:*

*(1) Inclusion of these entries is required starting with CREX edition 2.*

*(2) If inclusion of international data sub-category is required, Note 2 under Regulation B/C30.1.1 applies.*

*(3) Note 3 under Regulation B/C30.1.1 applies.*

*(4) If an NMHS performs conversion of CLIMAT data produced by another NMHS, Note 4 under Regulation B/C30.1.1 applies.*
____

*B/C30.2 Monthly values from a land station <3 07 071>*

*B/C30.2.1 Surface station identification; time, horizontal and vertical coordinates*

*<3 01 090>*

*B/C30.2.1.1 Station identification*

____
WMO block number station (0 01 001) and WMO station number (0 01 002) shall be always reported as a non-missing value.

Station or site name (0 01 015) shall be reported as published in _Weather Reporting_ (WMO-No. 9), Volume A – Observing Stations, provided that the station name does not exceed 20 characters. A shortened version of the name shall be reported otherwise.

Type of station (0 02 001) shall be reported to indicate the type of the station operation (manned, automatic or hybrid).
____

*B/C30.2.1.2 Date/time (of beginning of the month)*

____
Date <3 01 011> and time <3 01 012> shall be reported, i.e. year (0 04 001), month (0 04 002), day (0 04 003) and hour (0 04 004), minute (0 04 005) of beginning of the month *for which the monthly values are reported.* Day (0 04 003) shall be set to 1 and both hour (0 04 004) and minute (0 04 005) shall be set to 0.
____

*B/C30.2.1.3 Horizontal and vertical coordinates*

____
*Latitude (0* *05 001) and longitude* (0 06 001) of the station shall be reported in degrees with precision in 10^–5^ of a degree.

Height of station ground above mean sea level (0 07 030) and height of barometer above mean sea level (0 07 031) shall be reported in metres with precision in tenths of a metre.

Note: The official altitude of the aerodrome (HA in Volume A) shall not be used to report Height of station ground above mean sea level 0 07 030 in BUFR or CREX messages from aerodromes. Those are two different vertical coordinates. "Height of station ground above mean sea level" for each station should be made available to the encoding centre concerned, which may be a centre within the same NMHS or other NMC/RTH.
____

*B/C30.2.2 Monthly mean values of pressure, temperature, extreme temperatures and vapour pressure; standard deviation of daily mean temperature*

____
The monthly mean values of pressure, pressure reduced to mean sea level or geopotential height, temperature, extreme temperatures and vapour pressure shall be reported. Any missing element shall be reported as a missing value.
____

*B/C30.2.2.1 Reference period for the data of the month*

____
Monthly data (with the exception of precipitation data) are recommended to be reported for one-month period, corresponding to the local time (LT) month [_Handbook on CLIMAT and CLIMAT TEMP Reporting_ (WMO/TD-No.1188)]. In that case, short time displacement (0 04 074) shall specify the difference between UTC and LT (set to _non-positive values in the eastern hemisphere, non-negative values in the western hemisphere_).

Time period (0 04 023) represents the number of days in the month for which the data are reported, and shall be expressed as a _positive value_ in days.

Note: A BUFR (or CREX) message shall contain reports for one specific month only. [71.1.4]
____

*B/C30.2.2.2 First-order statistics* – Code table 0 08 023

____
This datum shall be set to 4 (mean value) to indicate that the following entries represent mean values of the elements (pressure, pressure reduced to mean sea level or geopotential height, temperature, extreme temperatures and vapour pressure) averaged over the one-month period.
____

*B/C30.2.2.3 Monthly mean value of pressure*

____
*Monthly mean value of* pressure shall be reported using 0 10 004 (Pressure) in pascals (with precision in tens of pascals).
____

*B/C30.2.2.4 Monthly mean value of pressure reduced to mean sea level*

____
*Monthly mean value of* pressure reduced to mean sea level shall be reported using 0 10 051 (Pressure reduced to mean sea level) in pascals (with precision in tens of pascals), if the air pressure at mean sea level can be computed with reasonable accuracy.
____

*B/C30.2.2.5 Monthly mean value of geopotential height*

____
*Monthly mean value of* geopotential height of a standard level shall be reported using 0 10 009 (Geopotential height) in geopotential metres from high-level stations which cannot give pressure at mean sea level to a satisfactory degree of accuracy. The standard isobaric level is specified by the preceding entry Pressure (0 07 004).
____

*B/C30.2.2.6 Height of sensor above local ground*

____
Height of sensor above local ground (0 07 032) for temperature and humidity measurement shall be reported in metres (with precision in hundredths of a metre).

This datum represents the actual height of temperature and humidity sensors above ground at the point where the sensors are located.

Note: If the height of the sensor was changed during the period specified, the value shall be that which existed for the greater part of the period.
____

*B/C30.2.2.7 Monthly mean value of temperature*

____
*Monthly mean value of* temperature shall be reported using 0 12 101 (Temperature/air temperature) in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius). Temperature data shall be reported with precision in hundredths of a degree even if they are available with the accuracy in tenths of a degree.

Notes:

{empty}(1) This requirement is based on the fact that conversion from the Kelvin to the Celsius scale has often resulted into distortion of the data values.

{empty}(2) Temperature t (in degrees Celsius) shall be converted into temperature T (in kelvin) using equation: T = t + 273.15.
____

*B/C30.2.2.8 Indicator to specify observing method for extreme temperatures* – Code table 0 02 051

____
This datum shall be set to 1 (maximum/minimum thermometers) or to 2 (automated instruments) or to 3 (thermograph) to indicate observing method for extreme temperatures.

Note: If the observing method for extreme temperatures was changed during the period specified, the code figure shall be that which existed for the greater part of the period.
____

*B/C30.2.2.9 Monthly mean value of maximum temperature*

____
*Monthly mean value of maximum* temperature shall be reported in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius).

Notes:

{empty}(1) Notes 1 and 2 under Regulation B/C30.2.2.7 shall apply.

*(2) The monthly mean value of maximum* *temperature shall be reported using 0 12 118 (Maximum temperature at height specified, past 24 hours). The height is specified by the preceding entry 0 07 032. Principal time of daily reading of maximum* *temperature (0 04 051) indicates the end of the 24-hour period to which the daily maximum temperature refers.*
____

*B/C30.2.2.10 Monthly mean value of minimum temperature*

____
*Monthly mean value of minimum* temperature shall be reported in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius).

Notes:

{empty}(1) Notes 1 and 2 under Regulation B/C30.2.2.7 shall apply.

*(2) The monthly mean value of minimum* *temperature shall be reported using 0 12 119 (Minimum temperature at height specified, past 24 hours). The height is specified by the preceding entry 0 07 032. Principal time of daily reading of minimum* *temperature (0 04 052) indicates the end of the 24-hour period to which the daily minimum temperature refers.*
____

*B/C30.2.2.11 Monthly mean value of vapour pressure*

____
*Monthly mean value of vapour* pressure shall be reported using 0 13 004 (*Vapour* pressure) in pascals (with precision in tens of pascals).
____

*B/C30.2.2.12 First-order statistics* – Code table 0 08 023

____
This datum shall be set to missing to indicate that the following entries do not represent the monthly mean values.
____

*B/C30.2.2.13 Standard deviation of daily mean temperature*

____
Standard deviation of daily mean temperature (0 12 151) shall be reported in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius). [71.3.1]
____

*B/C30.2.2.14 Number of days in the month for which values are missing*

____
*Number of days in the month for which values are missing shall be reported using Total number of missing entities (0* *08 020) being preceded by* Qualifier for number of missing values in calculation of statistic (0 08 050) in each of the required five replications (1 02 005)*.*

Qualifier for number of missing values in calculation of statistic (0 08 050) is:

– Set to 1 (pressure) in the first replication;

– Set to 2 (temperature) in the second replication;

– Set to 4 (vapour pressure) in the third replication;

– Set to 7 (maximum temperature) in the fourth replication;

– Set to 8 (minimum temperature) in the fifth replication.

The *number of days in the month for which values of the parameter are missing, shall be reported using 0 08 020 in the corresponding replication.*
____

*B/C30.2.3 Monthly duration of sunshine*

*B/C30.2.3.1 Total sunshine duration*

____
The monthly values of total duration of sunshine shall be reported in hours using Total sunshine (0 14 032) and the percentage of the normal that that value represents shall be reported using Total sunshine (0 14 033). Any missing element shall be reported as a missing value.

Notes:

{empty}(1) If the percentage of the normal is 1% or less but greater than 0, Total sunshine 0 14 033 shall be set to 1.

{empty}(2) If the normal is zero hours, _Total sunshine 0_ _14_ _033 shall be set to 510_.

{empty}(3) If the normal is not defined, Total sunshine 0 14 033 shall be set to missing.

{empty}[71.3.3]
____

*B/C30.2.3.2 Number of days in the month for which sunshine data are missing*

____
*Number of days in the month for which sunshine data are missing shall be reported using Total number of missing entities (0 08 020) being preceded by* Qualifier for number of missing values in calculation of statistic (0** **08 050) set to 6 (sunshine duration)*.*
____

*B/C30.2.4 Number of days with parameters beyond certain thresholds; number of days with thunderstorm and hail*

____
*Number of days in the month with* parameters beyond certain thresholds and with thunderstorm and hail **shall be reported using Total number (0 08 022) being preceded by C**ondition for which number of days of occurrence follows (0** **08 052) in each of the required eighteen replications (1** **02 018)*.*

Condition for which number of days of occurrence follows (0** **08 052) is:

– Set to 0 (mean wind speed over 10-minute period ≥ 10 m s^–1^);

– Set to 1 (mean wind speed over 10-minute period ≥ 20 m s^–1^);

– Set to 2 (mean wind speed over 10-minute period ≥ 30 m s^–1^);

– Set to 3 (maximum temperature < 273.15 K);

– Set to 4 (maximum temperature ≥ 298.15 K);

– Set to 5 (maximum temperature ≥ 303.15 K);

– Set to 6 (maximum temperature ≥ 308.15 K);

– Set to 7 (maximum temperature ≥ 313.15 K);

– Set to 8 (minimum temperature < 273.15 K);

– Set to 16 (snow depth > 0.00 m);

– Set to 17 (snow depth > 0.01 m);

– Set to 18 (snow depth > 0.10 m);

– Set to 19 (snow depth > 0.50 m);

– Set to 20 (horizontal visibility < 50 m);

– Set to 21 (horizontal visibility < 100 m);

– Set to 22 (horizontal visibility < 1** **000 m);

– Set to 23 (occurrence of hail);

– Set to 24 (occurrence of thunderstorm) in the last replication.

The *number of days in the month with* parameters beyond the specified thresholds and with thunderstorm and hail *shall be reported using 0 08 022 in the corresponding replication.*

*Note: Number of days in the month with* horizontal visibility beyond the specified thresholds is the number of days with visibility less than 50, 100 and 1** **000 m, respectively, _irrespective of the duration of the period_ during which horizontal visibility below the specified thresholds was observed or recorded.
____

*B/C30.2.5 Occurrence of extreme values of temperature and wind speed*

*B/C30.2.5.1 Height of sensor above local ground (for temperature)*

____
Height of sensor above local ground (0 07 032) for temperature measurement shall be reported in metres (with precision in hundredths of a metre).

This datum represents the actual height of temperature sensor above ground at the point where the sensor is located.
____

*B/C30.2.5.2 Occurrence of the highest daily mean temperature*

____
*The day on which the highest daily mean temperature occurred shall be reported using Day (0* *04 003). If the highest daily mean temperature occurred on only one day, the preceding entry 0* *08 053 (Day of occurrence qualifier) shall be set to 0. If the highest daily mean temperature occurred on more than one day, the first day shall be reported for 0* *04 003 and the preceding entry 0* *08 053 shall be set to 1. [71.6.1]*
____

* +
*

____
*Highest daily mean* temperature (0 12 152) shall be reported in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius).

Note: Notes 1 and 2 under Regulation B/C30.2.2.7 shall apply.
____

*B/C30.2.5.3 Occurrence of the lowest daily mean temperature*

____
*The day on which the lowest daily mean temperature occurred shall be reported using Day (0* *04 003). If the lowest daily mean temperature occurred on only one day, the preceding entry 0* *08 053 (Day of occurrence qualifier) shall be set to 0. If the lowest daily mean temperature occurred on more than one day, the first day shall be reported for 0* *04 003 and the preceding entry 0* *08 053 shall be set to 1. [71.6.1]*

*Lowest daily mean* temperature (0 12 153) shall be reported in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius).

Note: Notes 1 and 2 under Regulation B/C30.2.2.7 shall apply.
____

*B/C30.2.5.4 Occurrence of the highest air temperature of the month*

____
*The day on which the highest air temperature occurred shall be reported using Day (0* *04 003). If the highest air temperature occurred on only one day, the preceding entry 0* *08 053 (Day of occurrence qualifier) shall be set to 0. If the highest air temperature occurred on more than one day, the first day shall be reported for 0* *04 003 and the preceding entry 0* *08 053 shall be set to 1. [71.6.1]*

*The highest air* temperature of the month shall be reported using 0 12 101 (Temperature/air temperature), preceded by first-order statistics (0 08 023) set to 2 (maximum value). The temperature shall be reported in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius).

Note: Notes 1 and 2 under Regulation B/C30.2.2.7 shall apply.
____

*B/C30.2.5.5 Occurrence of the lowest air temperature of the month*

____
*The day on which the lowest air temperature occurred shall be reported using Day (0* *04 003). If the lowest air temperature occurred on only one day, the preceding entry 0* *08 053 (Day of occurrence qualifier) shall be set to 0. If the lowest air temperature occurred on more than one day, the first day shall be reported for 0* *04 003 and the preceding entry 0* *08 053 shall be set to 1. [71.6.1]*

*The lowest air* temperature of the month shall be reported using 0 12 101 (Temperature/air temperature), preceded by first-order statistics (0 08 023) set to 3 (minimum value). The temperature shall be reported in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius).

Note: Notes 1 and 2 under Regulation B/C30.2.2.7 shall apply.
____

*B/C30.2.5.6 Height of sensor above local ground (for wind measurement)*

____
Height of sensor above local ground (0 07 032) for wind measurement shall be reported in metres (with precision in hundredths of a metre).

This datum represents the actual height of wind sensors above ground at the point where the sensors are located.
____

* +
*

*B/C30.2.5.7 Type of instrumentation for wind measurement* – Flag table 0 02 002

____
This datum shall be used to specify whether the wind speed was measured by certified instruments (bit No. 1 set to 1) or estimated on the basis of the Beaufort wind scale (bit No. 1 set to 0), and to indicate the original units for wind speed measurement. Bit No. 2 set to 1 indicates that wind speed was originally measured in knots and bit No. 3 set to 1 indicates that wind speed was originally measured in kilometres per hour. Setting both bits No. 2 and No. 3 to 0 indicates that wind speed was originally measured in metres per second.

In CREX, type of instrumentation for wind measurement (0 02 002) shall be reported in octal representation. For example, if wind speed was measured by instruments in knots (bit No. 1 and bit No. 2 set to 1), then this datum shall be reported as 14.
____

*B/C30.2.5.8 Occurrence of the highest instantaneous wind speed of the month*

____
*The day on which the highest instantaneous wind speed occurred shall be reported using Day (0* *04 003). If the highest instantaneous wind speed occurred on only one day, the preceding entry 0* *08 053 (Day of occurrence qualifier) shall be set to 0. If the highest instantaneous wind speed occurred on more than one day, the first day shall be reported for 0* *04 003 and the preceding entry 0* *08 053 shall be set to 1. [71.6.1]*

*The highest instantaneous wind speed* of the month shall be reported using 0 11 046 (Maximum *instantaneous wind speed*) in metres per second (with precision in tenths of a metre per second).
____

*B/C30.2.6 Monthly precipitation data*

*B/C30.2.6.1 Date/time (of beginning of the one-month period for precipitation data)*

____
Day (0 04 003) and hour (0 04 004) of the beginning of the one-month period *for monthly precipitation data are reported.* Day (0 04 003) shall be set to 1 and hour (0 04 004) _shall be set to 6_.

Notes:

{empty}(1) In case of precipitation measurements, a month begins at 0600 hours UTC on the first day of the month and ends at 0600 hours UTC on the first day of the following month [_Handbook on CLIMAT and CLIMAT TEMP Reporting_ (WMO/TD-No.1188)].

{empty}(2) Year (0 04 001), month (0 04 002) and minute (0 04 005) of the beginning of the one-month period specified in the Regulation B/C30.2.1.2 apply.
____

*B/C30.2.6.2 Period of reference for precipitation data of the month*

____
Time period (0 04 023) represents the number of days in the month for which the monthly mean data are reported, and shall be expressed as a _positive value_ in days.

Note: A BUFR (or CREX) message shall contain reports for one specific month only. [71.1.4]
____

*B/C30.2.6.3 Height of sensor above local ground*

____
Height of sensor above local ground (0 07 032) for precipitation measurement shall be reported in metres (with precision in hundredths of a metre).

This datum represents the actual height of the rain gauge rim above ground at the point where the rain gauge is located.

Note: If the height of the sensor was changed during the period specified, the value shall be that which existed for the greater part of the period.
____

*B/C30.2.6.4 Total amount of precipitation of the month*

____
Total accumulated precipitation (0 13 060) which has fallen during the month shall be reported in kilograms per square metre (with precision in tenths of a kilogram per square metre).

Note: Trace shall be reported as “–0.1 kg m^–2^”.
____

*B/C30.2.6.5 Indication of frequency group*

____
*Frequency group in which* the total amount of precipitation *of the month falls shall be reported using Code table 0* *13 051 (Frequency group; precipitation).*

*Note: If for a particular month the total amount of precipitation is zero, the code figure for 0 13 051 shall be given by the highest number of quintile which has 0.0 as lower limit (e.g. in months with no rainfall in the 30-year period, 0 13 051 shall be set to 5). [71.3.2]*
____

*B/C30.2.6.6 Number of days with precipitation equal to or greater than 1 mm*

____
*Number of days in the month with precipitation equal to or greater than* 1 kilogram per square metre *shall be reported using 0 04 053 (Number of days in the month with precipitation equal to or greater than 1 mm).*
____

*B/C30.2.6.7 Number of days in the month for which precipitation data is missing*

____
*Number of days in the month for which precipitation is missing shall be reported using Total number of missing entities (0* *08 020) being preceded by* Qualifier for number of missing values in calculation of statistic (0 08 050) set to 5 (precipitation)*.*
____

*B/C30.2.7 Number of days with precipitation beyond certain thresholds*

____
*Number of days in the month with* precipitation beyond certain thresholds *shall be reported using Total number (0* **08 022) being preceded by C**ondition for which number of days of occurrence follows (0 08 052) in each of the required six replications (1 02 006)*.*

Condition for which number of days of occurrence follows (0 08 052) is:

– Set to 10 (precipitation ≥ 1.0 kg m^–2^) in the first replication;

– Set to 11 (precipitation ≥ 5.0 kg m^–2^);

– Set to 12 (precipitation ≥ 10.0 kg m^–2^);

– Set to 13 (precipitation ≥ 50.0 kg m^–2^);

– Set to 14 (precipitation ≥ 100.0 kg m^–2^);

– Set to 15 (precipitation ≥ 150.0 kg m^–2^) in the last replication.

The *number of days in the month with* precipitation beyond the specified thresholds *shall be reported using 0* *08 022 in the corresponding replication.*
____

*B/C30.2.8 Occurrence of extreme precipitation*

____
*The day on which the highest daily amount of precipitation occurred shall be reported using Day (0* *04 003). If the highest daily amount of precipitation occurred on only one day, the preceding entry 0* *08 053 (Day of occurrence qualifier) shall be set to 0. If the highest daily amount of precipitation occurred on more than one day, the first day shall be reported for 0* *04 003 and the preceding entry 0* *08 053 shall be set to 1. [71.6.1]*

*Highest daily amount of precipitation* (0 13 052) shall be reported in kilograms per square metre (with precision in tenths of a kilogram per square metre).

Note: *Trace* shall be reported as “–0.1 kg m^–2^”.
____

*B/C30.3 Monthly normals for a land station <3 07 072>*

____
*Meteorological Services shall submit to the Secretariat complete normal data of the elements for stations to be included in the CLIMAT bulletins. The same shall apply when Services consider it necessary to make amendments to previously published normal values. [71.4.1]*
____

*B/C30.3.1 Normals of pressure, temperatures, vapour pressure, standard deviation of daily mean temperature, and sunshine duration*

____
Normal values of pressure, pressure reduced to mean sea level or geopotential height, temperature, extreme temperatures, vapour pressure, standard deviation of daily mean temperature, and sunshine duration shall be reported. Any missing element shall be reported as a missing value.
____

*B/C30.3.1.1 Reference period for normal data*

____
R**eference period for calculation of the normal values of the elements shall be reported using** two consecutive entries 0 04 001 (Year). The first 0 04 001 shall express the year of beginning of the reference period and the second 0 04 001 shall express the year of ending of the reference period.

Note: The normal data reported shall be deduced from observations made over a specific period defined by the _Technical Regulations_ (WMO-No. 49__)__. [71.4.2]
____

*B/C30.3.1.2 Specification of the one-month period for which normals are reported*

____
The one-month period for which the normal values are reported shall be specified by month (0 04 002), day (0 04 003) being set to 1, hour (0 04 004) being set to 0, short time displacement (0 04 074) being set to (UTC – LT) and time period (0 04 022) being set to 1, i.e. 1 month.

Short time displacement (0 04 074) shall be set to _non-positive values in the eastern hemisphere, non-negative values in the western hemisphere_.
____

*B/C30.3.1.3 First-order statistics* – Code table 0 08 023

____
This datum shall be set to 4 (mean value) to indicate that the following entries represent mean values of the elements (pressure, pressure reduced to mean sea level or geopotential height, temperature, extreme temperatures, vapour pressure, standard deviation of daily mean temperature and sunshine duration) averaged over the reference period specified in Regulation B/C30.3.1.1.
____

*B/C30.3.1.4 Normal value of pressure*

____
*Normal value of* pressure shall be reported using 0 10 004 (Pressure) in pascals (with precision in tens of pascals).
____

*B/C30.3.1.5 Normal value of pressure reduced to mean sea level*

____
*Normal value of* pressure reduced to mean sea level shall be reported using 0 10 051 (Pressure reduced to mean sea level) in pascals (with precision in tens of pascals), if the air pressure at mean sea level can be computed with reasonable accuracy.
____

*B/C30.3.1.6 Normal value of geopotential height*

____
*Normal value of* geopotential height of a standard level shall be reported using 0 10 009 (Geopotential height) in geopotential metres from high-level stations which cannot give pressure at mean sea level to a satisfactory degree of accuracy. The standard isobaric level is specified by the preceding entry Pressure (0 07 004).
____

*B/C30.3.1.7 Height of sensor above local ground*

____
Regulation B/C30.2.2.6 shall apply.
____

*B/C30.3.1.8 Normal value of temperature*

____
*Normal value of* temperature shall be reported using 0 12 101 (Temperature/air temperature) in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius).

Note: Notes 1 and 2 under Regulation B/C30.2.2.7 shall apply.
____

*B/C30.3.1.9 Indicator to specify observing method for extreme temperatures* – Code table 0 02 051

____
Regulation B/C30.2.2.8 shall apply.
____

*B/C30.3.1.10 Normal value of maximum temperature*

____
*Normal value of maximum* temperature shall be reported in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius).

Notes:

{empty}(1) Notes 1 and 2 under Regulation B/C30.2.2.7 shall apply.

{empty}(2) Note 2 under Regulation B/C30.2.2.9 shall apply**.**
____

*B/C30.3.1.11 Normal value of minimum temperature*

____
*Normal value of minimum* temperature shall be reported in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius).

Notes:

{empty}(1) Notes 1 and 2 under Regulation B/C30.2.2.7 shall apply.

{empty}(2) Note 2 under Regulation B/C30.2.2.10 shall apply**.**
____

*B/C30.3.1.12 Normal value of vapour pressure*

____
*Normal value of vapour* pressure shall be reported using 0 13 004 (*Vapour* pressure) in pascals (with precision in tens of pascals).
____

*B/C30.3.1.13 Normal value of standard deviation of daily mean temperature*

____
Normal value of standard deviation of daily mean temperature shall be reported using 0 12 151 in kelvin (with precision in hundredths of a kelvin); if produced in CREX, in degrees Celsius (with precision in hundredths of a degree Celsius).
____

*B/C30.3.1.14 Normal of monthly sunshine duration*

____
Normal of monthly sunshine duration shall be reported in hours using 0 14 032 (Total sunshine).
____

*B/C30.3.2 Normals of precipitation*

____
Normal values of monthly amount of precipitation and of number *of days in the month with precipitation equal to or greater than 1 mm,* shall be reported. Any missing element shall be reported as a missing value.
____

*B/C30.3.2.1 Reference period for normal values of precipitation*

____
R**eference period for calculation of the normal values of precipitation shall be reported using** two consecutive entries 0 04 001 (Year). The first 0 04 001 shall express the year of beginning of the reference period and the second 0 04 001 shall express the year of ending of the reference period.

Note: The note under Regulation B/C30.3.1.1 shall apply.
____

*B/C30.3.2.2 Specification of the one-month period for which normals are reported*

____
The one-month period for which the normals of precipitation are reported shall be specified by month (0 04 002), day (0 04 003) being set to 1, hour (0 04 004) _being set to 6_ and time period (0 04 022) being set to 1, i.e. 1 month.

Note: Note 1 under Regulation B/C30.2.6.1 shall apply.
____

*B/C30.3.2.3 Height of sensor above local ground*

____
Regulation B/C30.2.6.3 shall apply.
____

*B/C30.3.2.4 First-order statistics* – Code table 0 08 023

____
This datum shall be set to 4 (mean value) to indicate that the following entries represent mean values of precipitation data, averaged over the reference period specified in Regulation B/C30.3.2.1.
____

*B/C30.3.2.5 Normal value of monthly amount of precipitation*

____
Normal value of monthly amount of precipitation shall be reported in kilograms per square metre (with precision in tenths of a kilogram per square metre) using 0 13 060 (Total accumulated precipitation).

Note: Trace shall be reported as “–0.1 kg m^–2^”.
____

*B/C30.3.2.6 Normal value of number of days with precipitation* ≥ *1 mm*

____
*Normal value of number of days in the month with precipitation equal to or greater than* 1 kilogram per square metre *shall be reported using 0* *04 053 (Number of days in the month with precipitation equal to or greater than 1 mm).*
____

*B/C30.3.3 Number of missing years*

____
*Number of missing years within the reference period shall be reported using Total number of missing entities (0* *08 020) being preceded by* Qualifier for number of missing values in calculation of statistic (0 08 050) in each of the required eight replications (1 02 008)*.*

Qualifier for number of missing values in calculation of statistic (0 08 050) is:

– Set to 1 (pressure) in the first replication;

– Set to 2 (temperature);

– Set to 3 (extreme temperatures);

– Set to 4 (vapour pressure);

– Set to 5 (precipitation);

– Set to 6 (sunshine duration);

– Set to 7 (maximum temperature);

– Set to 8 (minimum temperature) in the last replication.

The *number of missing years within the reference period for calculation of the normal values of the element shall be reported using 0* *08 020 in the corresponding replication.*

*Note:* The number of missing years within the reference period from the calculation of normal for mean extreme air temperature should be given, if available, for both the calculation of normal maximum temperature and for the calculation of normal minimum temperature in addition to the number of missing years for the extreme air temperatures reported under 0 08 020 preceded by 0 08 050 in which Figure 3 is used.
____

*B/C30.4 Regional or national reporting practices*

*B/C30.4.1 Data required by regional or national reporting practices*

____
No additional data are currently required by regional or national reporting practices for CLIMAT data in the _Manual on Codes_ (WMO-No. 306), Volume II.
____

*B/C30.4.2 Reference period for the data of the month*

____
If the regional or national reporting practices require reporting monthly data (with the exception of precipitation data) for one-month period different from the local time month as recommended in Regulation B/C30.2.2.1, short time displacement (0 04 074) shall be adjusted accordingly.
____

*B/C30.4.3 Date/time (of beginning of the period for monthly precipitation data)*

____
If the regional or national reporting practices require reporting monthly precipitation data for period different from the period recommended in Note 1 to Regulation B/C30.2.6.1, then hour (0 04 004) shall be adjusted accordingly. This regulation does not apply if the beginning of the period for monthly precipitation data starts on the last day of the previous month in UTC.
____

*B/C30.4.4 Date/time (of beginning of the one-month period for precipitation data on the last day of the previous month)*

____
If the regional or national reporting practices require reporting monthly precipitation data for period which starts on the last day of the previous month in UTC, template TM 307078 should be used. The beginning of the period for monthly precipitation data shall be specified by short time displacement (0 04 074) set to a relevant negative value. The beginning of one-month period for which the normals of precipitation are reported, shall be specified in a similar way.

_____________
____
